### ISSUE TITLE
sling 1.0.18 bug

### ISSUE THREAD

**Issue by maxlivi** [slingdata-io/sling-cli#10]
Hello,

The last update seems to not working properly'

## sling Version: 1.0.17 ( DB is postgres+ timescale)

0:57AM INF truncated table public.wh2a
10:57AM INF inserted 537 rows in 0 secs [1,732 r/s]
10:57AM INF execution succeeded
10:57AM WRN FYI, a new sling version is available (please run `sling update`)

## After updating to 1.0.18
10:59AM INF writing to target database [mode: truncate]
10:59AM INF streaming data
10:59AM INF created table public.WH2A
10:59AM INF truncated table public.WH2A
10:59AM INF execution failed
fatal:
~ 
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
~ 
~ execution failed
~ could not write to database
~ Could not insert from temp
~ could not get column list for public.WH2A
~ could not get column list for public.WH2A
did not find any columns for table: "public"."WH2A"

Reverting to 1.0.17 makes sling working as expected.

**Comment by flarco** [comment]
Thanks for reporting! Just released fix `v1.0.20`.
