### ISSUE TITLE
Environment variables in dbt profiles.yml

### ISSUE THREAD

**Issue by cdchan** [slingdata-io/sling-cli#102]
I like the idea of using dbt's `profiles.yml` to populate connections so that we don't have to define them multiple times, but our `profiles.yml` uses dbt's `env_var` interpolation to populate credential secrets. It looks like Sling directly reads in the YAML so no interpolation happens and the connection string (obviously) doesn't work.

Example `profiles.yml` using `env_var` in dbt documentation: https://docs.getdbt.com/reference/dbt-jinja-functions/env_var

A low priority enhancement but it would be neat if we could use our `profiles.yml` as is.

**Comment by flarco** [comment]
I like it.

**Comment by flarco** [comment]
Done, see https://github.com/flarco/dbio/commit/0d103d6a6efde76473bb333d44c1567e3734580c.
Will be in next release (#99).

**Comment by flarco** [comment]
v1.0.68 Released.
