### ISSUE TITLE
Enhance logging to add the stream name upon completion

### ISSUE THREAD

**Issue by ShahBinoy** [slingdata-io/sling-cli#103]
Hi,

Would it be possible to add the stream name to the last statement of a single stream sync
`INF wrote 653434 rows [39,692 r/s]`, if we can get the source table/object name in the log statement itself

`INF Completed stream <schema>.<table>. wrote 653434 rows [39,692 r/s]`

The way this helps is when out of process applications capture this information, they can atleast do some kind of checkpointing in their system to measure the total progress. 

This is quite helpful when doing a replication kind of flow

**Comment by flarco** [comment]
Done, see https://github.com/slingdata-io/sling-cli/pull/99/commits/3e35a6d4c204aa76fba0034595053f14833e2acb.
Will be in next release (#99)
