### ISSUE TITLE
Sling CLI always exits with code 1

### ISSUE THREAD

**Issue by ryandstoughton** [slingdata-io/sling-cli#106]
When running the Sling CLI, the command always exits with a status code of `1`.

```sh
sling -v 
echo $?
```

Produces
<img width="801" alt="Screenshot 2024-01-09 at 1 28 34 PM" src="https://github.com/slingdata-io/sling-cli/assets/46951044/d2d60882-c47c-42f0-8f93-8cd88fa6ca21">

This keeps the user from detecting real failures in the Sling process.

**Comment by flarco** [comment]
Hi, `-v` is not an accepted flag. See the message below `Expected a following arg for flag v, but it did not exist.`?

But, what you are referring is from the https://github.com/slingdata-io/sling-python release. The `sling` command returns `1`. Bug. Will fix for next release. Thanks for raising.

```
$ sling -v
sling - An Extract-Load tool | https://slingdata.io
Slings data from a data source to a data target.
Version 1.0.64

  Usage:
    sling [conns|run|update]

  Subcommands: 
    conns    Manage local connections in the sling env file
    run      Execute a run
    update   Update Sling to the latest version

  Flags: 
       --version   Displays the program version string.
    -h --help      Displays help with available flag, subcommand, and positional value parameters.

Expected a following arg for flag v, but it did not exist.
```

**Comment by flarco** [comment]
v1.0.68 Released.
