### ISSUE TITLE
Unable to connect to Clickhouse through Chproxy (http)

### ISSUE THREAD

**Issue by axelwas** [slingdata-io/sling-cli#108]
Hi,

First thanks @flarco for building Sling, it's a great tool that worked great for us to sync between databases.

I'm trying to build a pipeline to load data from Clickhouse and Sling is unable to connect. I'm getting this error : `read tcp [myIP]->[proxyIP]:443: i/o timeout`.
We use [CHproxy](https://www.chproxy.org/) to handle traffic to our Clickhouse instance and SSL is required.

While having no Golang experience, I tried to dive into the codebase. I found out that :
- Sling uses dbio, which uses the official Clickhouse go client to connect to Clickhouse
- According to the [Clickhouse client docs](https://github.com/ClickHouse/clickhouse-go?tab=readme-ov-file#http-support-experimental), to connect through an http proxy (CHproxy), one should either use a DSN starting with `http://`, or use OpenDB method and specify the protocol in the options.

In dbio, I found out that for Clickhouse db type, the url template always starts with `clickhouse://` (cf [here](https://github.com/flarco/dbio/blob/main/connection/connection.go#L547)). I wasn't able to make it work by manually specifying an url starting with `http://`. The Clickhouse connection object doesn't seem to be created using the OpenDB method, even though I found a test using it [here](https://github.com/flarco/dbio/blob/main/database/clickhouse_test.go#L34).

I would be amazing if you could look into that.

Thanks !

**Comment by flarco** [comment]
Thanks!

Look like what you want is achievable as noted here: https://github.com/ClickHouse/clickhouse-go?tab=readme-ov-file#http-support-experimental

I added the `http_url` option to override the connection string here: https://github.com/flarco/dbio/commit/999ae4278861afb2292aafd4296f1a636e3b5fe1

Can you [compile](https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#compiling-from-source) sling yourself with branch `v1.0.69` (#110), test and report back?

**Comment by axelwas** [comment]
Hi!

Works like a charm 🚀

To add precision, I needed to connect through https so my connection looks like this :
```
  CLICKHOUSE:
    type: clickhouse
    host: my_host
    user: my_user
    database: default
    http_url: https://my_user:my_password@my_host:443/default?secure=true
```

Out of pure curiosity, where exactly in the code is the connection established in dbio ?

Thanks @flarco !

**Comment by flarco** [comment]
Sling first creates a [generic connection object](https://github.com/flarco/dbio/blob/main/connection/connection.go#L49-L54), then calls the [AsDatabase](https://github.com/flarco/dbio/blob/main/connection/connection.go#L241) method to convert to a [database connection](https://github.com/flarco/dbio/blob/main/database/database.go#L55).

From there, the [Connect](https://github.com/flarco/dbio/blob/main/database/database.go#L519) is used.

The `dbio` lib definitely needs some clean up! Will get to it eventually.

**Comment by axelwas** [comment]
Thanks for the explanations! 

I'd be happy to contribute once I have some experience with Go.

When roughly are you gonna be releasing `v1.0.69` ?

**Comment by flarco** [comment]
Thinking this weekend. Want to solve another issue first.

**Comment by flarco** [comment]
Released. Closing.
