### ISSUE TITLE
Error when not specifying a schema

### ISSUE THREAD

**Issue by KacemHamza97** [slingdata-io/sling-cli#11]
Hey :)

While using the sling-cli for data transfer from a PostgreSQL database to a DuckDB database using the following command:
**Command ❌**
    &nbsp; &nbsp; &nbsp; &nbsp;  sling run --src-conn dvdrental_db --src-stream 'category' --tgt-conn duck_db_conn --tgt-object 'category'

I encountered an issue when not specifying a schema for the target table in DuckDB, resulting in the following error message:
Error: near line 1: Parser Error: zero-length delimited identifier at or near """"
LINE 1: create schema ""
I know that in DuckDB the default schema is public. I modified the command to include the schema explicitly, and it worked.
**Command ✅**
     &nbsp; &nbsp; &nbsp; &nbsp; sling run --src-conn dvdrental_db --src-stream 'category' --tgt-conn duck_db_conn --tgt-object 'public.category'
I guess that the problem occurs during command parsing in the target, as it appears that the code requires schema specification; otherwise, it throws an error.

**Comment by flarco** [comment]
Hey there, yes, it typically needs a schema, or you can set the default schema at the connection level. Try this:
```bash
export duck_db_conn='duckdb:///path/to/file.db?schema=public'
sling run --src-conn dvdrental_db --src-stream 'category' --tgt-conn duck_db_conn --tgt-object 'category'
```
Closing this since it's intended this way :). Let me know if you have suggestions.

**Comment by flarco** [comment]
You know what, since DUCKDB always has public, we can make this the default. Will change.

**Comment by KacemHamza97** [comment]
I appreciate your response, :) everything is working perfectly. My apologies for conflating "public" (the default schema for Postgres) with "main." (DuckDB).
