### ISSUE TITLE
Snowflake OBJECT type mapped as String not JSON

### ISSUE THREAD

**Issue by jmesterh** [slingdata-io/sling-cli#115]
I tried to look in the [source code ](https://github.com/flarco/dbio/blob/main/iop/dataset.go#L460)to see how JSON inference happens. It looks like there is a check, but it doesn't seem to be working for me?

I have a Snowflake table with OBJECT field type (JSON), when I load into BigQuery it arrives as String type not JSON type. I can override this if I explicitly set source_options.columns per-table, but it would be nice if this happened automatically as new tables will be added to this database and I am using schema.* as the replication stream.

**Comment by flarco** [comment]
Thanks, fixed (https://github.com/flarco/dbio/commit/44d23b5d016eb11b2fdc7fe84d90b97a1bdcfae4)

Here are where the data types are mapped (from and to):
- https://github.com/flarco/dbio/blob/main/database/templates/types_native_to_general.tsv
- https://github.com/flarco/dbio/blob/main/database/templates/types_general_to_native.tsv

Added to (#110)
