### ISSUE TITLE
Add run recursive flag for sling cli

### ISSUE THREAD

**Issue by Codykilpatrick** [slingdata-io/sling-cli#123]
Hey Sling team!

I am currently running sling with `sling run -c task.json`. For our situation it would be helpful to have a cli flag `-r` that would on completion run again.

I was wondering if this is possible or something that will be added in the future? Thanks again!

**Comment by flarco** [comment]
Hey @Codykilpatrick, not totally following what you're asking here. You're thinking of having sling re-run the same command again? Could you explain the reasoning? do you mean re-run when the task fails, or re-run regardless?

**Comment by Codykilpatrick** [comment]
Yes! I want the exact same command to run again. 

The premise behind this is we have a MySQL database, that is constantly getting new data, and we are syncing into a PostGres database. I'm thinking re-run regardless but not sure what would be best?

**Comment by flarco** [comment]
Oh ok, cool! Can you tell me how you are running sling? Are you using some sort of scheduler? Thinking that would be the place to do it, like making it run every 5 min or something.

**Comment by Codykilpatrick** [comment]
Yeah! So far for testing I have been running just as a cli-input. But the final solution would be to add it to a docker compose stack.

So after running docket compose, sling runs on a loop constantly pulling from the MYSQL database.

As far as frequency goes we are actually hoping to have it run every second. This works in a python or bash script but hopefully a container running the command 'run sling -c task.json' is the final goal.

**Comment by flarco** [comment]
Ah ok cool. Sounds like you just want to loop run continuously.
I think your best bet is to create a bash script, and put the sling command inside a [while loop](https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_09_02.html). You can even put a `sleep 1` command right after to wait before re-running. Once added to your Dockerfile / container, you can run it and sling will just run indefinitely. Should do the trick!

**Comment by Codykilpatrick** [comment]
Marking this as closed, no features needed!
