### ISSUE TITLE
Add Linux ARM64 Target Docker / Python

### ISSUE THREAD

**Issue by johnoscott** [slingdata-io/sling-cli#130]
When i build this a Docker image on my M1 Mac it fails

```Dockerfile
FROM python:3.11-buster
# fails on macOS Apple Silicon
RUN pip install sling
```

Error is 
```
...
 > [2/2] RUN pip install sling:                                                                                                                                                                   
1.296 Collecting sling                                                                                                                                                                            
1.386   Downloading sling-1.0.71.tar.gz (170.5 MB)                                                                                                                                                
35.08      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 4.0 MB/s eta 0:00:00                                                                                                            
38.87   Preparing metadata (setup.py): started                                                                                                                                                    
39.29   Preparing metadata (setup.py): finished with status 'error'
39.29   error: subprocess-exited-with-error
39.29   
39.29   × python setup.py egg_info did not run successfully.
39.29   │ exit code: 1
39.29   ╰─> [14 lines of output]
39.29       Traceback (most recent call last):
39.29         File "<string>", line 2, in <module>
39.29         File "<pip-setuptools-caller>", line 34, in <module>
39.29         File "/tmp/pip-install-nsa_8kdm/sling_05d20e156c1546f0a7a2d061a43a2a2b/setup.py", line 6, in <module>
39.29           version = cli('--version', return_output=True).strip().replace('Version: ', '')
39.29                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
39.29         File "/tmp/pip-install-nsa_8kdm/sling_05d20e156c1546f0a7a2d061a43a2a2b/sling/__init__.py", line 300, in cli
39.29           raise E
39.29         File "/tmp/pip-install-nsa_8kdm/sling_05d20e156c1546f0a7a2d061a43a2a2b/sling/__init__.py", line 293, in cli
39.29           for line in _exec_cmd(cmd, stdin=sys.stdin, stdout=stdout, stderr=stderr):
39.29         File "/tmp/pip-install-nsa_8kdm/sling_05d20e156c1546f0a7a2d061a43a2a2b/sling/__init__.py", line 325, in _exec_cmd
39.29           raise Exception(f'Sling command failed:\n{lines}')
39.29       Exception: Sling command failed:
39.29       []
39.29       [end of output]
39.29   
39.29   note: This error originates from a subprocess, and is likely not a problem with pip.
39.29 error: metadata-generation-failed

```

This is presumably because there is no current release of sling for linux on ARM.

I have a workaround which is to specify the image platform, but these run slower as emulated amd64 on ARM (using Rosetta in latest Docker Desktop for macOS )

```Dockerfile
# force platform to be the only currently supported linux for sling which is amd64 (ie. Intel/AMD )
FROM --platform=linux/amd64 python:3.11-buster
RUN pip install sling
```

Could you please :

1. create an arm64 linux release
2. update the official docker image (not related to my problem - but enabled by this arm release)

**Comment by flarco** [comment]
Yes, will have to think about this. Currently using github-actions [here](https://github.com/slingdata-io/sling-cli/blob/main/.github/workflows/build-release.yml) to build/release, but no arm runners are available from GH. See https://github.com/actions/runner-images/issues/5631.

**Comment by johnoscott** [comment]
I could try building sling using a Go toolchain within an ARM Docker image (on my Mac). How would i then `pip install sling` to use the local (built) sling binary ?

**Comment by flarco** [comment]
You would just move the binary into the sub `bin` folder, see https://github.com/slingdata-io/sling-python/blob/main/sling/__init__.py#L10. Then do `pip install -e .` inside the `sling-python` folder (cloned from [repo](https://github.com/slingdata-io/sling-python))

**Comment by flarco** [comment]
Well hold on, you're trying to use python or docker? I gave python instruction above.

**Comment by flarco** [comment]
I'm also looking at https://docs.orbstack.dev/ and https://tart.run/ to see if I can use my mac as a self-hosted arm64 linux gh runner (inside container).

**Comment by johnoscott** [comment]
OK I will try that in the mean time. My quick research i also suggesting that the only way for you that github actions will support an arm linux build is to use a self-hosted runner:

> As of my last update in early 2023, Docker was not natively supported on the macOS ARM runners provided by GitHub Actions. GitHub's hosted runners for macOS are provided as x86_64 virtual machines, even though the underlying hardware might be ARM-based (like with the M1 chips). GitHub Actions does not currently offer native M1/macOS ARM runners.

> For x86_64 macOS runners, you can use Docker directly since they come with Docker pre-installed. However, if you're looking for native ARM support, you would have to use self-hosted runners on your own ARM-based Mac hardware.

**Comment by kgantchev** [comment]
@johnoscott 

> My quick research i also suggesting that the only way for you that github actions will support an arm linux build is to use a self-hosted runner....

Pardon me if I'm intruding here, but if you're considering MacOS runners, may I suggest giving [FlyCI](https://flyci.net) a try? We offer MacOS M1 and M2 runners (ARM64). For public repos, we offer 500 mins/month of free M1 usage (4 vCPUs, 7 GB RAM, 28 GB storage).

The setup is super easy: 

1. Install the [FlyCI GitHub app](https://github.com/apps/flyci-prod).
2. Give the FlyCI app permissions to this repo.
3. Change your runs-on flag whenever you implement the ARM64 MacOS workflow:

```diff
jobs:
ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
      steps:
      - name: 👀 Checkout repo
         uses: actions/checkout@v4
```

Do you think this might be a good option for[sling-cli](https://github.com/slingdata-io/sling-cli)? 

Web: [flyci.net](https://flyci.net/) | Twitter: [flyciapp](https://twitter.com/flyciapp) | LinkedIn: [FlyCI](https://linkedin.com/company/flyci) | Discord: [FlyCI](https://discord.gg/JyCjh439da)

**Comment by wearpants** [comment]
Yes please

**Comment by flarco** [comment]
The binary for `linux_arm64` is now available in the latest release for manual download: https://github.com/slingdata-io/sling-cli/releases
Docker and Python version are not working yet.

**Comment by johnoscott** [comment]
Thats awesome. Thankyou 🙏 ! What's involved in making Docker on ARM (ie. Docker Desktop on Apple Silicon) work ?

**Comment by flarco** [comment]
Rebuilding this Dockerfile: https://github.com/slingdata-io/sling-cli/blob/main/cmd/sling/Dockerfile

The current one uses x64 ubuntu so it just didn't work, see failures [here](https://github.com/slingdata-io/sling-cli/actions/workflows/build-release.yml)

Moreover, the current Dockerfile is loaded with extra tools for bulk loading (for Oracle, SQL server and MySQL), so will see if those tools offer arm64 versions. I think i'll just release a lightweight arm64 Dockerfile next release (without those tools), then increment from there.

**Comment by johnoscott** [comment]
A lightweight arm64 Dockerfile without Oracle & SQLServer support would suit me as I am currently using PostgreSQL only. I am keen to get a native ARM version running so this would be the best option for me presently. I will let you know how it works for me once released.

**Comment by johnoscott** [comment]
I am ready to test v1.1.4 ; when will you release it @flarco ?

**Comment by flarco** [comment]
Soon, after completing https://github.com/slingdata-io/sling-cli/issues/149.

**Comment by johnoscott** [comment]
@flarco curious to know - how did you end up building the linux-arm version ? Did you use a remote GitHub runner ?

**Comment by flarco** [comment]
Used https://tart.run/quick-start/
Tart works nicely, but having issues with [goreleaser](https://goreleaser.com/)

**Comment by flarco** [comment]
FYI `slingdata/sling:1.1.4-arm64` is available.
Working on `slingdata/sling:latest` for multi-platform.

**Comment by johnoscott** [comment]
1.1.4 is not on (pypi)[https://pypi.org/project/sling/] yet. Can I pip install directly from GitHub ?

**Comment by flarco** [comment]
> Can I pip install directly from GitHub ?

Hmm, not sure that will work. I changed the dependencies in `sling-python`, need to release there first.
I should get to it soon though.

**Comment by johnoscott** [comment]
Might be temporary, but I can't install latest `1.1.5` version at all using `pip install`

```sh
pip install --no-cache-dir sling==1.1.5
Collecting sling==1.1.5
  Downloading sling-1.1.5.tar.gz (5.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/johnscott/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/johnscott/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/johnscott/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/77/7lt_q0j96y93_n0hyy4d45p00000gn/T/pip-build-env-6ilrs395/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/77/7lt_q0j96y93_n0hyy4d45p00000gn/T/pip-build-env-6ilrs395/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/77/7lt_q0j96y93_n0hyy4d45p00000gn/T/pip-build-env-6ilrs395/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/77/7lt_q0j96y93_n0hyy4d45p00000gn/T/pip-build-env-6ilrs395/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 41, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/77/7lt_q0j96y93_n0hyy4d45p00000gn/T/pip-install-8qbqy0ry/sling_4f580d79bbc241f6b91ea13a3fb0aa8d/../README.md'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by flarco** [comment]
Yeah, just went through various issues. Should be good now.
Can you try `pip install sling==1.1.5.post1`?

**Comment by johnoscott** [comment]
similar error as above with `1.1.5` when i try to build Docker image :

```Dockerfile
FROM python:3.11-buster

RUN echo "sling==1.1.5b0" > requirements.txt

RUN pip install --no-cache-dir -r requirements.txt


```

`docker build -t slingtemp .`

```sh
Sending build context to Docker daemon…
[==================================================>] 19.23kB
Done

Step 1/5 : FROM python:3.11-buster
 ---> 3a19b4d6ce44
Step 2/5 : RUN apt-get -y update && apt-get -y install git
 ---> Using cache
 ---> a04b797c1b8f
Step 3/5 : RUN pip install --upgrade pip
 ---> Using cache
 ---> b23fd501f407
Step 4/5 : COPY requirements.txt .
 ---> Using cache
 ---> ef898ac40f2b
Step 5/5 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Running in 886153856a41
Collecting sling==1.1.5 (from -r requirements.txt (line 1))
  Downloading sling-1.1.5.tar.gz (5.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tt62euz8/sling_6d264c1f9c8a49b5b2461e450ef15967/setup.py", line 41, in <module>
          long_description=open(os.path.join(os.path.dirname(__file__), '..', 'README.md')).read(),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-tt62euz8/sling_6d264c1f9c8a49b5b2461e450ef15967/../README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error response from daemon: The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
Failed to deploy '<unknown> Dockerfile: Dockerfile': Can't retrieve image ID from build stream


```

**Comment by flarco** [comment]
just deleted `sling==1.1.5b0`, try `sling==1.1.5.post1`

**Comment by flarco** [comment]
Followed the convention: https://stackoverflow.com/questions/13919830/update-a-pypi-package

**Comment by flarco** [comment]
Closing this, just tested and installed just fine. Let me know if any issues.

**Comment by johnoscott** [comment]
Confirmed working for me now 👍 

```sh
docker build -t sling-arm-test .                                  
```

Confirm it runs

```sh
docker run --rm sling-arm-test sling --version

```

Confirm architecture is ARM-64 (not AMD-64 aka x86)

```
docker inspect --format='{{.Os}}/{{.Architecture}}' sling-arm-test
linux/arm64
```

**Comment by johnoscott** [comment]
all looking good building my own Docker image. However the official docker image seems to pull the wrong platform #162
