### ISSUE TITLE
MariaDB Incremental Error

### ISSUE THREAD

**Issue by gu-xie** [slingdata-io/sling-cli#135]
Testing Sling with MariaDB seems to throw an exception when attempting to perform `INCREMENTAL` load.

`Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'tgt`

Seems that it's harcoding "`***`" to the schema section of qualifying the object.

``` sql
DELETE FROM `***`.`datain_policy_t` tgt
WHERE EXISTS (
    SELECT 1
    FROM `***`.`datain_policy_t_tmp` src
    WHERE src.`policy_number` = tgt.`policy_number`
)
;
```

**Comment by flarco** [comment]
Ah, the `***` is just masked, to not leak sensitive information via logging, so that's not it.
Interesting, this `DELETE` query works in MySQL. Can you try it manually? And try to modify it to see what's wrong?
I don't have a MariaDB test db online, only MySQL.

**Comment by flarco** [comment]
Also if they have a MERGE statement, we can use that

**Comment by gu-xie** [comment]
@flarco Thanks for pointing this out.

Seems MariaDB does not support an alias on a single table delete statement.
https://stackoverflow.com/questions/75089998/sql-delete-with-exists-is-not-working-in-mariadb

If you specify the name of the table without aliasing, it will work fine.

**Comment by flarco** [comment]
Thanks, fixed in https://github.com/slingdata-io/sling-cli/pull/136

**Comment by gu-xie** [comment]
Thank you @flarco !
