### ISSUE TITLE
Make access_key_id and secret_access_key optional for AWS S3 connections

### ISSUE THREAD

**Issue by jkglasbrenner** [slingdata-io/sling-cli#139]
The [AWS S3 connection](https://docs.slingdata.io/connections/file-connections/s3) requires the user to provide an `access_key_id` and `secret_access_key`. Sling will raise an error if either of these keys is not provided. The check for this I think happens here: https://github.com/flarco/dbio/blob/3f229fb59feb3630afdb452dc53faeade6ccb3cc/filesys/fs_s3.go#L73

It would be great if these parameters were optional. Requiring these keys means that AWS users cannot leverage other methods for providing AWS credentials to the AWS SDK, such as [using an IAM role to grant permissions to applications running on Amazon EC2 instances](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html).

For context: my company manages my AWS account and their networking security policy makes it difficult to use automated tools that require the access and secret keys. By default, we have to [use multi-factor authentication (MFA) to generate temporary tokens](https://repost.aws/knowledge-center/authenticate-mfa-cli), which is fine if you're using the AWS CLI but not if you need to run things in a scheduled pipeline. If we're doing something automated that can't rely on MFA, they want us to use IAM roles instead. I would really like to leverage Sling in one of my projects, but this is unfortunately a blocker for us.

**Comment by jkglasbrenner** [comment]
As a follow-up, I saw that the `dbio` repo is being migrated into this repo for the v1.1.0 release. Since the relevant code was here, I wanted to validate that making the `access_key_id` and `secret_access_key` parameters optional would allow Sling to leverage IAM roles on an EC2 instance. I started with this function:

https://github.com/slingdata-io/sling-cli/blob/a291bcece9fa867b33448ca13770fcf1381553b6/core/dbio/filesys/fs_s3.go#L71-L102

I modified it to the following:

```go
func (fs *S3FileSysClient) Connect() (err error) {

	endpoint := fs.GetProp("ENDPOINT")
	region := fs.GetProp("REGION", "DEFAULT_REGION")
	if region == "" {
		region = defaultRegion
	}

	// https://docs.aws.amazon.com/sdk-for-go/api/service/s3/
	awsConfig := &aws.Config{
		Region:                         aws.String(region),
		S3ForcePathStyle:               aws.Bool(true),
		DisableRestProtocolURICleaning: aws.Bool(true),
		Endpoint:                       aws.String(endpoint),
		// LogLevel: aws.LogLevel(aws.LogDebugWithHTTPBody),
	}

	if fs.GetProp("ACCESS_KEY_ID") != "" && fs.GetProp("SECRET_ACCESS_KEY") != "" {
		awsConfig.Credentials = credentials.NewStaticCredentials(
			fs.GetProp("ACCESS_KEY_ID"),
			fs.GetProp("SECRET_ACCESS_KEY"),
			fs.GetProp("SESSION_TOKEN"),
		)
	} else if !(fs.GetProp("ACCESS_KEY_ID") == "" && fs.GetProp("SECRET_ACCESS_KEY") == "") {
		return g.Error("ACCESS_KEY_ID and SECRET_ACCESS_KEY must be both set or both empty")
	}

	fs.session, err = session.NewSession(awsConfig)
	if err != nil {
		err = g.Error(err, "Could not create AWS session")
		return
	}

	return
}
```

I compiled and tested it on my EC2 instance, and Sling was able to use the IAM role to acquire AWS credentials. I'll admit that I'm not a Go developer, so it's possible this introduces a bug elsewhere that I'm not expecting. But since this seems to work, I'm going to use this workaround in my project for the time being.

**Comment by flarco** [comment]
Nice, thanks I'll test it out and commit into https://github.com/slingdata-io/sling-cli/pull/137

**Comment by flarco** [comment]
Commit: https://github.com/slingdata-io/sling-cli/pull/137/commits/ecaf01c7a06edb1e52aab70aa5fcedfd04bacc67
Closing, will release soon.

**Comment by ataft** [comment]
Any docs or advice on how to use IAM Role instead of access key?

**Comment by flarco** [comment]
Can you try with env_var `AWS_ROLE_ARN`? or set up `role_arn` in your default AWS profile?
