### ISSUE TITLE
Quoted Columns

### ISSUE THREAD

**Issue by dluftspring** [slingdata-io/sling-cli#14]
Not sure if the option exists and I was reading the docs wrong but for a replication between Snowflake and Postgres it looks like sling doesn't correctly read or provide an option to specify that the Snowflake identifiers are quoted

**Comment by flarco** [comment]
Hi, can you share more information? Such as what the qualified name of the snowflake column is, and how it is creating it in Postgres.

**Comment by flarco** [comment]
This should be fix in the new version here: https://github.com/slingdata-io/sling-cli/releases/tag/v1.0.31
Can you download the binary, test and let me know if it works for you?

**Comment by dluftspring** [comment]
This is also working now!
