### ISSUE TITLE
Starrocks: random timeouts when using stream load feature

### ISSUE THREAD

**Issue by metalshanked** [slingdata-io/sling-cli#159]
Hi, 

Seem to be getting timeouts when using Sling w/ stream load enabled and connecting to FE as below
The timeout errors on load happen with 10-15 secs
Starrocks : 3.2.2 w/ Shared Data mode (only FE and CN)

Connecting to CN URL directly works better but does timeout sometimes.

```
--- database_starrocks.go:327 func3 ---
~ could not perform request
--- http.go:100 ClientDo ---
Put "http://@starrocks-cluster-fe-search.starrocks.svc.cluster.local:8030/api/a/b/_stream_load": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by flarco** [comment]
Hi, ok, I put 300 sec of timeout. Commit is [here](https://github.com/slingdata-io/sling-cli/pull/152/commits/f5082757d9ae7564787e93b681ade5b0718c02cc).
If you would like to test now, you can [compile the binary](https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#compiling-from-source) from branch [`v1.1.4`](https://github.com/slingdata-io/sling-cli/pull/152) and test.

**Comment by flarco** [comment]
Closing. Feel free to re-open if the issue persists.

**Comment by metalshanked** [comment]
Sure. Thank you!
