### ISSUE TITLE
Is it possible to use kerberos authentication for MSSQL?

### ISSUE THREAD

**Issue by ted-gooch-sh** [slingdata-io/sling-cli#160]
It looks like it may not be supported in the go driver referenced, but is supported in the Microsoft fork. Curious if anyone's gotten this working with Sling.

**Comment by flarco** [comment]
Looks like there isn't any progress here: https://github.com/denisenkom/go-mssqldb/issues/383

**Comment by flarco** [comment]
Closing. Feel free to re-open if external Issue is solved/closed.
