### ISSUE TITLE
Support for Mongo DB

### ISSUE THREAD

**Issue by MarcinWylot** [slingdata-io/sling-cli#163]
Is it possible to add support for MongoDB as source/target?

**Comment by flarco** [comment]
Yes, source is planned. 
Target however is a big lift. Will have to come later on, since Mongo is not a SQL database (see [WriteToDB](https://github.com/slingdata-io/sling-cli/blob/main/core/sling/task_run_write.go#L96) function).

**Comment by mcpeterson** [comment]
Amazing.  Another vote here for MongoDB as a source :)

**Comment by flarco** [comment]
Source added in v1.1.14!
