### ISSUE TITLE
when load snowflake_to_starrocks, all rows are filled with null value.

### ISSUE THREAD

**Issue by MarkovWangRR** [slingdata-io/sling-cli#180]
sling run --src-conn EXTERNAL_SNOWFLAKE --src-stream 'markov_sling_schema.customer' --tgt-conn STARROCKS_TEST --tgt-object 'db_test_load_1.customer_from_snowflake' --mode full-refresh

I just load the full data from table CUSTOMER in snowflake into StarRocks, it seems the rows count is right, but all values is NULL.

**Comment by MarkovWangRR** [comment]
I just use a TPCH table CUSTOMER will 1000 rows for a sample test.

**Comment by alberttwong** [comment]
do you have the parquet or CSV so he can duplicate the data load?

**Comment by MarkovWangRR** [comment]
Local parquet/csv into StarRocks can really work.

This is the **csv file** that i export from SF into local. You can try to load it into Snowflake. 

[snowflake_customer_1.csv](https://github.com/slingdata-io/sling-cli/files/14339777/snowflake_customer_1.csv)

**Snowflake DDL:**

create or replace TABLE MARKOV_SLING_DB.MARKOV_SLING_SCHEMA.CUSTOMER (
	C_CUSTKEY NUMBER(38,0),
	C_NAME VARCHAR(25),
	C_ADDRESS VARCHAR(40),
	C_NATIONKEY NUMBER(38,0),
	C_PHONE VARCHAR(15),
	C_ACCTBAL NUMBER(15,2),
	C_MKTSEGMENT VARCHAR(10),
	C_COMMENT VARCHAR(117)
);

**Comment by MarkovWangRR** [comment]
Also when i choose the full-refresh model to do the ingestion, i observe that all the value column (like C_CUSTKEY) will be auto cast into varchar column in StarRocks. This behaviour confuse me a little.

**Comment by flarco** [comment]
Thanks, I was able to reproduce when loading via FE.
When I don't use the FE (don't provide `fe_url`), which loads via INSERT it works fine.
Also look at the `_sling_row_id` which is the hash key, has values, but not the rest of the columns. 🤔 

```
$ sling run --src-conn starrocks --src-stream public.test1k --stdout -l 10
6:46AM INF connecting to source database (starrocks)
6:46AM INF reading from source database
6:46AM INF writing to target stream (stdout)
id,name,age,city,create_date,rating,is_happy,passchar,passcode,unichar,unitext,_sling_row_id
,,,,,,,,,,,2cctpTZX6Ts6p8SOqVT9wNaxJlL
,,,,,,,,,,,2cctpPyIRUH0Y0UpC8fS9aM2fcT
,,,,,,,,,,,2cctpPCb0qEZAmJfQNF81MZVBSC
,,,,,,,,,,,2cctpN5NNF3WZ9C35J3ChYIQRvX
,,,,,,,,,,,2cctpPDqiNgXJDlu3aBbvfjCgoV
,,,,,,,,,,,2cctpP6wUHp7j69cXBtKqQNYv9p
,,,,,,,,,,,2cctpQKl9E3lxeuMPnTLmHpbbDI
,,,,,,,,,,,2cctpNC4yzLZbJtCW7wY3BgbhTX
,,,,,,,,,,,2cctpPEOHBwu6gvR5cVcupUR2VW
,,,,,,,,,,,2cctpSrMg9RUlZ1u0e91uJHObU6
```

**Comment by flarco** [comment]
The thing is, if I use MySQL Postres as source, instead of Snowflake, loading via FE works fine... Looking closer.

**Comment by flarco** [comment]
Got it. Snowflake outputs its columns as uppercase, and when loading via FE, the  `columns` header was set with uppercase from snowflake, and Starrocks is sensitive to column casing when loading via FE. Needed to normalize the column casing to match StarRocks. Applied fixed in #181, will release later this week. Thanks for reporting!
Closing.

**Comment by MarkovWangRR** [comment]
Hi Sling team, 
Really thank you for your efffort on solving the StarRocks&Snowflake integration issues.
Because i am familiar with StarRocks, so i have some suggestion for Sling from my testing experience:
1. StarRocks is sensitive of column casing, so when we do the auto-table-creation, when need to ensure the schema from source file/external database the same as the schema in StarRocks.
2. When we inference the schema from source file like PARQUET/CSV, i ovserve that value column will be auto-casted into varchar column in StarRocks. That doesn't make sense.

sling run --src-stream 'file:///Users/wangyouzhuo/Downloads/customer01.parquet'  --tgt-conn CELERDATA_SAAS --tgt-object 'db_test_load_1.customer_parquet' --mode full-refresh --src-options '{"flatten":true}'

**Comment by flarco** [comment]
Sure:

1. When Sling ingests from a file, it attempts to clean up the names. Files can sometimes have weird characters. See [here](https://github.com/slingdata-io/sling-cli/blob/3756bc6415b48e8e20c1c40be71f01a0cd06ee40/core/dbio/iop/csv.go#L40-L77) for CSV clean up function. Can you give more details on why it should match exactly? If you load again with sling, it will match the differences deterministically and insert correctly.
2. Can you elaborate? What do you mean the `value` column? Maybe you could upload the `customer01.parquet` file, so I can test.

**Comment by MarkovWangRR** [comment]
For CSV, the default behaviour of cleaning up the names does make sense. For parquet, it seems sling can auto fetch the schema from the source files well.
And i just test the snowflake/parquet with starrocks, it looks like everythings work well. No more issues. 
Done well Sling team! thank you.
