### ISSUE TITLE
It seems source custom SQL can't be terminated by ; . 

### ISSUE THREAD

**Issue by MarkovWangRR** [slingdata-io/sling-cli#197]
wangyouzhuo@markovwong file % sling run --src-conn EXTERNAL_SNOWFLAKE_SSB_100GB --src-stream 'SELECT * FROM SSB_SF100GCL.CUSTOMER LIMIT 30000;' --tgt-conn CELERDATA_SAAS --tgt-object 'DB_SLING_TEST.CUSTOMER_FULL' --mode full-refresh

6:13PM INF connecting to source database (snowflake)
6:13PM INF connecting to target database (starrocks)
6:13PM INF reading from source database
6:13PM INF execution failed
fatal:
~ SQL Error
001003 (42000): SQL compilation error:
syntax error line 2 at position 49 unexpected ';'.
wangyouzhuo@markovwong file % sling run --src-conn EXTERNAL_SNOWFLAKE_SSB_100GB --src-stream 'SELECT * FROM SSB_SF100GCL.CUSTOMER LIMIT 30000' --tgt-conn CELERDATA_SAAS --tgt-object 'DB_SLING_TEST.CUSTOMER_FULL' --mode full-refresh

6:13PM INF connecting to source database (snowflake)
6:13PM INF connecting to target database (starrocks)
6:13PM INF reading from source database
6:13PM INF writing to target database [mode: full-refresh]
6:14PM INF streaming data
6:14PM INF importing into StarRocks via stream load
13s 30,000 2666 r/s                     
6:14PM INF dropped table `db_sling_test`.`customer_full`
6:14PM INF created table `db_sling_test`.`customer_full`
6:14PM INF inserted 30000 rows into `db_sling_test`.`customer_full` in 28 secs [1,060 r/s] 
6:14PM INF execution succeeded

![截屏2024-02-29 18 14 19](https://github.com/slingdata-io/sling-cli/assets/101642945/b50f95f8-6fa0-4af8-9bc1-ce11b585f151)

**Comment by flarco** [comment]
Can you remove the `;` at the end of you SQL?

`--src-stream 'SELECT * FROM SSB_SF100GCL.CUSTOMER LIMIT 30000'`
instead of 
`--src-stream 'SELECT * FROM SSB_SF100GCL.CUSTOMER LIMIT 30000;'`

**Comment by flarco** [comment]
That's a driver limitation. Sling could auto remove it, or you could.

**Comment by flarco** [comment]
👍
