### ISSUE TITLE
CLI options syntax confusion (--target-opts)

### ISSUE THREAD

**Issue by nickolay** [slingdata-io/sling-cli#20]
Attempting to specify inline options in `--target-opts` results in a rather confusing experience.

In #19 you said:
> It accepts YAML or JSON syntax, but it has to be surrounded by quotes from the command line.
>
>  * YAML syntax: --tgt-options '{use_bulk: false}'
>  * JSON syntax: --tgt-options '{"use_bulk": false}'

...but my tests in cmd.exe on Windows demonstrate that:

* `'{use_bulk: false}'` and `'{"use_bulk": false}'` trigger **yaml: found unexpected end of stream**
    ```
    c:\temp>type test.csv | sling run --tgt-conn MSSQL --tgt-object dbo.test -d --tgt-options '{use_bulk: false}'
    fatal:
    --- sling.go:398 func1 ---
    --- sling.go:439 cliInit ---
    --- cli.go:283 CliProcess ---
    ~ invalid target options -> '{use_bulk:
    --- sling_logic.go:100 processRun ---
    yaml: found unexpected end of stream
    ```
* `'{use_bulk:false}'` yields **yaml: unmarshal errors:**
    ```
    c:\temp>type test.csv | sling run --tgt-conn MSSQL --tgt-object dbo.test -d --tgt-options '{use_bulk:false}'
    fatal:
    ~
    ~ invalid target options -> '{use_bulk:false}'
    yaml: unmarshal errors:
      line 1: cannot unmarshal !!str `{use_bu...` into sling.TargetOptions
    ```
* `{use_bulk: false}` and `{"use_bulk": false}` yield **yaml: line 1: did not find expected node content**
    ```
    c:\temp>type test.csv | sling run --tgt-conn MSSQL --tgt-object dbo.test -d --tgt-options {use_bulk: false}
    fatal:
    ~
    ~ invalid target options -> {use_bulk:
    yaml: line 1: did not find expected node content
    ```
* `{use_bulk:false}` and `"{use_bulk:false}"` are silently ignored
    ```
    c:\temp>type test.csv | sling run --tgt-conn MSSQL --tgt-object dbo.test -d --tgt-options {use_bulk:false}
    ...SQL Server BCP Import Error
    ```
* `"{use_bulk: false}"`, `{'use_bulk':false}`, and `"{'use_bulk':false}"` work as expected:
    ```
    c:\temp>type test.csv | sling run --tgt-conn MSSQL --tgt-object dbo.test -d --tgt-options "{use_bulk: false}"
    ```

```
c:\temp>type test.csv
a;b;c
1;2;3

c:\temp>sling --version
Version: 1.0.39

c:\temp>type %USERPROFILE%\.sling\env.yaml
# Environment Credentials for Sling CLI

# See https://docs.slingdata.io/sling-cli/environment

connections:
  MSSQL:
    type: sqlserver
    url: sqlserver://etl:REDACTED@sqlsrv:1433/master

variables: {}
```

**Comment by flarco** [comment]
Thanks for the details. I was able to reproduce.

Crazy, same command works fine on Mac and Linux. Did not think the flag parsing would be an issue on Windows. Admittedly, there isn't a CI testing flow for windows.

Will fix soon.

**Comment by flarco** [comment]
Ah ok, so you are using DOS? 
I just tried in Powershell and it worked as expected with `--tgt-options '{use_bulk: false}'`.
@nickolay Can you try in powershell? DOS is weird with the flags.

**Comment by nickolay** [comment]
Normally I use bash, and switched to cmd.exe only because it's still the default shell on Windows.

I realize that some of the listed errors are cases of "user error" (e.g. not quoting spaces) and some are shell-dependent (single quotes in cmd.exe), but the major contributor to the confusion IMHO is trying to parse YAML _(which I didn't even know you could meaningfully inline)_ from a command line parameter. This is the first tool, I come across, that does this.

In powershell:
* `"{use_bulk:false}"` is ignored
* `'{use_bulk:false}'` is ignored
* `'{"use_bulk":false}'` ignored, even though it's valid JSON
* `'{"use_bulk": false}'` works

**Comment by flarco** [comment]
Hi, looked into it, seems you need a space after colon. Check with https://onlineyamltools.com/convert-yaml-to-json.
- `'{use_bulk: false}'` works, does not use `bcp`
- `'{"use_bulk":false}'` works for me, does not use `bcp`
-  `'{use_bulk:false}'` does not work, uses `bcp`

**Comment by nickolay** [comment]
> '{"use_bulk":false}' works for me, does not use bcp

I can confirm it works in bash, but not in powershell for some reason (still on sling v1.0.39):
```
PS C:\temp> cat test.csv |sling run --tgt-conn MSSQL --tgt-object dbo.test -d --tgt-options '{"use_bulk":false}'
...
~ SQL Server BCP Import Command -> bcp dbo.test_tmp in C:\Users\NICKOL~1\AppData\Local\Temp\sqlserver.dbo.test_tmp.1.csv1979018883 -S **** -d master -U etl -P **** -t , -m 1 -c -q -b 50000 -F 2 -e /dev/stderr
```

> you need a space after colon [...] '{use_bulk:false}' does not work, uses bcp

Technically you're right. But interpreting this as `{"use_bulk:false": null}` and silently ignoring the unknown option is very confusing to the end-user, which was the point of this issue.

Anyway, if you don't want to limit inline options to JSON (which would IMO result in much more sensible error messages), I can live with it — thanks for taking the time to consider it!

**Comment by flarco** [comment]
@nickolay can you update to 1.0.40? Should work for bcp. 
Thanks will add a warning that the inputted string was not correctly parsed. I myself also thought `{use_bulk:false}` would be valid!

**Comment by flarco** [comment]
@nickolay Check out the test cases below. Makes sense?
Added JSON support, as well as YAML. Before it was only YAML. See #29.

```go
{
	input:    `{"use_bulk":false}`,
	expected: map[string]any{"use_bulk": false},
},
{
	input:    `{"use_bulk": false}`,
	expected: map[string]any{"use_bulk": false},
},
{
	input:    `{use_bulk: false}`,
	expected: map[string]any{"use_bulk": false},
},
{
	input:    `use_bulk: false`,
	expected: map[string]any{"use_bulk": false},
},
{
	input:       `{use_bulk:false}`,
	shouldError: true,
},
{
	input:       `use_bulk:false`,
	shouldError: true,
},
```

**Comment by nickolay** [comment]
Sorry for the delay, and thanks for adding the additional diagnostics!

For my own reference, the changes sling 1.0.39->1.0.48 are:

* cmd.exe
  * `{use_bulk:false}` and `"{use_bulk:false}"`, which used to be silently ignored, now print:
     ```
      ~
      ~ invalid target options -> {use_bulk:false}
      invalid key: use_bulk:false
      ```
     (it's still not trivial to guess it's because YAML requires a space after the colon, but oh well)
* PowerShell (5.1):
  * `"{use_bulk:false}"`, `'{use_bulk:false}'`, and `'{use_bulk:false}'` which used to be ignored, now also display `invalid key: use_bulk:false`
  * `'{"use_bulk":false}'` also displays `invalid key: use_bulk:false` now, because [powershell cannot be trusted to pass quotes to applications correctly](https://stackoverflow.com/questions/6714165/powershell-stripping-double-quotes-from-command-line-arguments).

**Comment by flarco** [comment]
Thanks. I changed the error message, which will reflect in next release:

```go
if strings.Contains(k, ":") {
  return options, g.Error("invalid key: %s. Try adding a space after the colon.", k)
}
```
