### ISSUE TITLE
parse_uuid transform on ms sql parses some (or all) strings that are 16 characters long as uuids

### ISSUE THREAD

**Issue by tnschneider** [slingdata-io/sling-cli#202]
Example:

Source
![image](https://github.com/slingdata-io/sling-cli/assets/8934680/30d57720-24f6-4c3c-ae63-b9561f04199c)

Target
![image](https://github.com/slingdata-io/sling-cli/assets/8934680/6be314df-aadc-4672-baaa-f1684e921ec3)

**Comment by flarco** [comment]
Yes, thanks, not ideal.
I know what's wrong, will fix soon.

**Comment by flarco** [comment]
OK, done, give the new release a shot.

**Comment by tnschneider** [comment]
Fixed, thanks!
