### ISSUE TITLE
Hash transformation

### ISSUE THREAD

**Issue by tomsej** [slingdata-io/sling-cli#203]
When working with PII data, it would be great to have a transformation (SHA, MD5…) that would hash sensitive columns.

BTW thanks for this great project!

**Comment by flarco** [comment]
Great suggestion.

**Comment by flarco** [comment]
Done. 
Added transforms `hash_md5`, `hash_sha256` and `hash_sha512`.
See [here](https://github.com/slingdata-io/sling-cli/blob/faa750d77c454374e967c64e38dd69f641e3d4ed/core/sling/transforms.go#L35-L37).
Will be available in v1.1.14.
Closing.

**Comment by tomsej** [comment]
Thanks a lot!!
