### ISSUE TITLE
Support for comma as decimal separator

### ISSUE THREAD

**Issue by comino** [slingdata-io/sling-cli#207]
I tried to import a CSV dataset with a comma as a decimal separator in numbers. I found no option that would parse the numbers not as varchars. I tried forcing the column type to "decimal" without success, it's still parsed to varchar. Do I miss any config option that would make this work? 

Maybe it's a feature others might find useful too. I would propose another option "decimal_format" ( since we already have "datetime_format") or decimal_seperator ( more declarative).  Or maybe we autodetect the number format as there are only two formats? 

I really like the simplicity of sling, thanks a lot for your work!! <3

**Comment by flarco** [comment]
Thanks, can you give a sample file of your csv (at least the decimal values)? 
Also, what database are loading into? If you could share your config file and the output with debug mode (`-d`), that would be helpful.

**Comment by comino** [comment]
Sure! 

CSV sample:
`
Obj;PropId;Value;TimeStamp;TimeStampISO
BB01;85;45,3828582763672;133245162327228051;2023-03-28T22:30:32Z
BB01;85;40,3816032409668;133245181140278467;2023-03-28T23:01:54Z
BB01;85;45,3858795166016;133245207233952957;2023-03-28T23:45:23Z
BB01;85;50,388298034668;133245209487304477;2023-03-28T23:49:08Z
BB01;85;45,3873443603516;133245215378614197;2023-03-28T23:58:57Z
BB01;85;40,3829345703125;133245217529463186;2023-03-29T00:02:32Z
BB01;85;35,3816719055176;133245220376169720;2023-03-29T00:07:17Z
BB01;85;40,3844985961914;133245230678878369;2023-03-29T00:24:27Z
BB01;85;45,3865814208984;133245234406821951;2023-03-29T00:30:40Z
`

Sing command: 
`
cat sample.csv | sling run --tgt-conn MYSQL --tgt-object 'rysta.raw_data' --trim_space true --src-options '{"columns":{Value":"decimal"}}'
`

Tested with MySQL and SQLite, here mySQL DDL: 
`
CREATE TABLE `raw_data` (
  `obj` text,
  `propid` int DEFAULT NULL,
  `value` text,
  `timestamp` bigint DEFAULT NULL,
  `timestampiso` datetime(6) DEFAULT NULL,
  `_sling_loaded_at` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
`

Sling uses strconv.ParseFloat(s, 64) to parse the string and there is no option in strconv to change the decimal seperator, hence we probably need to replace "," with "." : 
https://github.com/slingdata-io/sling-cli/blob/2e4babad75071702717a963378132b23c5061263/core/dbio/iop/stream_processor.go#L94

**Comment by flarco** [comment]
Done. It will replace it automatically, no need to add another source option.

See https://github.com/slingdata-io/sling-cli/pull/208/commits/6c9e4cbc86453646460562bae5d8040528a2d15d

Thanks for the suggestion and donation! Will release 1.1.14 in a few days.
