### ISSUE TITLE
Oracle target - global environment variables values and related columns

### ISSUE THREAD

**Issue by fabrice-etanchaud** [slingdata-io/sling-cli#209]
Hi !

From my tests with 1.1.12, I found that if I set the following global environment variables : 

SLING_LOADED_AT_COLUMN : 

_sling_loaded_at column does not contain a timestamp but an integer value. Can I cast it ?

SLING_ROW_NUM_COLUMN : 

_sling_row_num column contains the same value for all records, that is the total count of loaded records.

But even if oracle create these columns, one cannot use them, because they start with a '_', and have an invalid name.

Am I doing something wrong ?
I just discovered sling, and it's amazing !

Thank you  !

**Comment by flarco** [comment]
Hi, thanks. I had replied to your email (perhaps it went to spam).

For Oracle, you need to properly qualify the fields starting with `_`. So do `select "_SLING_LOADED_AT" from ...`

- Converting from epoch unix into a date in Oracle: https://stackoverflow.com/a/49677974/2295355
- for `SLING_ROW_NUM_COLUMN`, will look into it. It should increment by 1 every row.

**Comment by flarco** [comment]
Closing. Feel free to re-open.
