### ISSUE TITLE
sql in a stream does not seem to override default sql

### ISSUE THREAD

**Issue by fabrice-etanchaud** [slingdata-io/sling-cli#211]
Hi, doing some testing with 1.1.12, in a oracle-oracle configuration. I found that if I set a default sql, and then define a custom sql in a stream, the default sql is still used.

Am I doing something wrong ?

Thank you  !

**Comment by flarco** [comment]
Hi, can you share the replication config you are using?

**Comment by flarco** [comment]
Actually, the logic is missing!
Now added: https://github.com/slingdata-io/sling-cli/pull/208/commits/489268eb719a5dd095ff1eccc801066b52bc8680
Thanks, closing. Should work when v1.1.14 is released.

**Comment by fabrice-etanchaud** [comment]
incredible ! Thank you !
