### ISSUE TITLE
Target-Schema with "-" not accepted in CLI

### ISSUE THREAD

**Issue by azngeek** [slingdata-io/sling-cli#23]
If the target database cointains "-", an error will be thrown.

`
sling run \
 --src-stream file:///file.json \
 --src-options 'flatten: true' \
 --tgt-conn MYSQL_WAREHOUSE \
 --tgt-object `db-123`.test \
 --mode full-refresh
`

The error is:

`
fatal:
~
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
~
~ execution failed
~ could not write to database
~ could not create temp table test_tmp
~ Error checking & creating schema
did not specify schema. Please specify schema in object name.
`

**Comment by flarco** [comment]
can you try with a quote around it?  just like you did for `src-options`.

```
sling run --src-stream file:///file.json --src-options 'flatten: true' --tgt-conn MYSQL_WAREHOUSE --tgt-object 'db-123.test' --mode full-refresh 
```

**Comment by flarco** [comment]
You might need to add backticks for MySQL since there is a hyphen in there:
```
--tgt-object '`db-123`.test'
```

**Comment by azngeek** [comment]
I already tried that and there is still the error. Here is the full log.

`
$ ~/deploy/sling run \
>  --src-stream file:///articles.json \
>  --src-options 'flatten: true' \
>  --tgt-conn MYSQL_WAREHOUSE \
>  --tgt-object '`db-6`.articles' \
>  --mode full-refresh
6:17PM INF connecting to target database (mysql)
6:17PM INF reading from source file system (file)
6:17PM INF writing to target database [mode: full-refresh]
6:17PM INF execution failed
fatal:
~
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
~
~ execution failed
~ could not write to database
~ could not drop table db-6.articles_tmp
~ Error for drop table if exists db-6.articles_tmp
~ Could not execute SQL
~ Error executing [tx: false] drop table if exists ***.articles_tmp
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-6.articles_tmp' at line 1
`

**Comment by flarco** [comment]
thanks, will take a look

**Comment by flarco** [comment]
@azngeek  can you run `sling update`, and try again with latest version?

**Comment by azngeek** [comment]
This also resolved the issue. Maybe you can also add this to the documentation, as from my experience databases with dashes are common.
