### ISSUE TITLE
flatten-Option does not work

### ISSUE THREAD

**Issue by azngeek** [slingdata-io/sling-cli#24]
I tried the example from the blog https://blog.slingdata.io/import-json-files-into-mysql and that JSON worked. However this json will result in an error. 

This happens, because there is the special character '@' in the keys. I will do a cleanup from my side but maybe this was not intended.

`
[
  {
    "Kennung": "M",
    "Sortennummer": "75118",
    "Bezeichnung1": "--Geschenk-Gutschein 3--",
    "Bilder": {
      "Bild": {
        "@NR": "2",
        "Datei": "G75118_2.jpg"
      }
    }
  }
]
`

**Comment by flarco** [comment]
Thanks, do you mind running it with `-d` for debug mode, and paste the output here?

**Comment by flarco** [comment]
@azngeek can you run `sling update`, and try again with latest version?

**Comment by azngeek** [comment]
It works now! Fantastic ;)
