### ISSUE TITLE
gzip support 

### ISSUE THREAD

**Issue by alberttwong** [slingdata-io/sling-cli#255]
## Feature Description

gzip support

**Comment by alberttwong** [comment]
https://github.com/StarRocks/starrocks/issues/42624

**Comment by flarco** [comment]
Thanks. This is only compatible with the FILES command, correct?

**Comment by alberttwong** [comment]
I was generalizing the issue with StarRocks as an example.   I believe StarRocks' plan is to support gzip in files.

**Comment by flarco** [comment]
Already supported:
<img width="762" alt="image" src="https://github.com/slingdata-io/sling-cli/assets/7671010/3072fdc3-e7f9-490e-aad6-6c3f24783f9a">

**Comment by alberttwong** [comment]
Nice... I didn't know Sling Data supports compression at source already.
