### ISSUE TITLE
allow errors when loading csv files into StarRocks

### ISSUE THREAD

**Issue by rishabhkaushal07** [slingdata-io/sling-cli#256]
## Feature Description

Hi, StarRocks has a feature where you can [set error tolerance](https://docs.starrocks.io/docs/sql-reference/sql-statements/data-manipulation/STREAM_LOAD/#set-error-tolerance) when loading a csv file into a starrocks db.

sling does not have this feature and will error out if one of the rows of a CSV file has errors or can't be loaded.
It would be good to have this feature as it would still ingestion of the rows without out right failing.

**Comment by flarco** [comment]
Hi, done: https://github.com/slingdata-io/sling-cli/pull/253/commits/6a7495ae3578d32845348188199edb3ede4794b5

Will just have to set as a connection property:
 ```bash
export STARROCKS='{ type: starrocks,
  url: "starrocks://myuser:mypass@host.ip:9030/mydatabase",
  fe_url: "http://host.ip:8030",  max_filter_ratio: "0.3", strict_mode: "true" }'
```
