### ISSUE TITLE
MongoDB - Unable to connect to source

### ISSUE THREAD

**Issue by alexismanuel** [slingdata-io/sling-cli#277]
## Issue Description

- Description of the issue: 
When executing the command `sling conns test SRC_MONGO`, I am faced with an error saying sling failed to ping the server. I use the hostname, user and password which were already working for an existing Airbyte source connection (my goal here is to replace it with sling hopefully).
Do you have any idea on how I can troubleshoot this ? Thanks in advance for your insights !

- Sling version (`sling --version`): Version: 1.2.6

- Operating System (`linux`, `mac`, `windows`): mac

- Replication Configuration: None yet

- Log Output (please run command with `-d`): 
the -d flag does not work for the conns test command
```
➜ sling conns test SRC_MONGO                                                                                                                          
fatal:
~ Failed to ping mongo server
server selection error: context deadline exceeded, current topology: { Type: Unknown, Servers: [{ Addr: <hostname>.mongodb.net:27017, Type: Unknown, Last error:  connection(<hostname>:27017[-12]) incomplete read of message header: read tcp <ip>:50443-><ip>:27017: read: connection reset by peer: connection(<hostname>:27017[-12]) incomplete read of message header: read tcp <ip>:50443-><ip>:27017: read: connection reset by peer }, ] }
```

**Comment by flarco** [comment]
Strange. Since I can't test on my side, could you try another client on your machine?
See threads in https://stackoverflow.com/questions/73552273/mongodb-server-selection-error-due-network-timeout

Also, this person says it got fixed after enabling TLS: https://stackoverflow.com/questions/72856947/mongodb-insertmany-incomplete-read-of-message-header-context-deadline-exceed
Could you try that? I pushed a change to accept a CA file (if needed) in branch [`1.2.7`](https://github.com/slingdata-io/sling-cli/pull/274). Could you compile the binary and test it out? See docs with new `cert_ca_file` key: https://docs.slingdata.io/connections/database-connections/mongodb

**Comment by alexismanuel** [comment]
I think you are right about the TLS because it was enabled for my Airbyte connection. However I did not need to provide any cert_ca_file, just to enable a prop `tls` to true, here is an example of the yaml config:
```yaml
configuration:
  user: <my_user>
  database: <my_db>
  password: <my_pwd>
  auth_source: admin
  instance_type:
    tls: true
    host: <my_host>
    port: 27017
    instance: standalone
```

I will try to find how to generate the file for the test on the 1.2.7, but do you think it could be feasible to have a similar way as above to enable TLS ?

**Comment by flarco** [comment]
Found this: 
<img width="805" alt="image" src="https://github.com/slingdata-io/sling-cli/assets/7671010/6c9a5323-5d8b-473e-921e-3255d472b7bd">

I'll add the more explicit key `tls`, but can you try with the url and add `tls=true`?

**Comment by alexismanuel** [comment]
It works with the `tls=true` query arg ! So as of now I am able to make it work with the following setup on 1.2.6:
```bash
sling conns set TEST type=mongodb url="mongob://<user>:<password>@<hostname>:<port>/?tls=true"
INF connection `TEST` has been set in /<user>/.sling/env.yaml. Please test with `sling conns test TEST`

sling conns test TEST
INF success!
```

**Comment by flarco** [comment]
Great!
