### ISSUE TITLE
File destination - have a skip option for same file name instead of replace/delete

### ISSUE THREAD

**Issue by dduong1603** [slingdata-io/sling-cli#282]
Right now Sling deletes the file and replace it with a new file. This changes the update time of the file and potentially impacts downstream workflow. Can we get a skip/ignore-existing option instead?

**Comment by flarco** [comment]
In your situation, is the stream incremental? is the source a database or file?

**Comment by dduong1603** [comment]
The stream is not incremental, and the source is a file (trying to do a file to file transfer), and we want to write that same file to multiple destinations, and if something fails midway, we want to retry the process but skip the destinations that already have that file. We could probably hack together something in our process to ignore the CLI call for those particular destinations, but thought it would be nice to have a flag in the CLI call 😄

**Comment by dduong1603** [comment]
I guess this also applies to multiple streams within a single destination/replication, and we want to skip the file/stream that has the same destination name

**Comment by flarco** [comment]
Cool, will add a `ignore_existing` key in target-options.

**Comment by flarco** [comment]
Should be completed this week for upcoming release #289 (likely this weekend).

**Comment by flarco** [comment]
Done (https://github.com/slingdata-io/sling-cli/pull/289/commits/cc6b5d1a7586e9649bf036ba8245037a195d39f9). Feel free to compile binary and test.
