### ISSUE TITLE
Default incremental mode prevents using full-refresh on stream level

### ISSUE THREAD

**Issue by somiandras** [slingdata-io/sling-cli#292]
## Issue Description

- Description of the issue: 

I have a long list of replication defined in my yaml, most of which are `incremental` with `id` as primary key and `update_dt` as update key, so I add this part to my `replication.yaml`:

```
defaults:
  mode: incremental
  primary_key: [id]
  update_key: update_dt

streams:
  ...
```

A few of my replication has to be `full-refresh` though, so I override defaults on stream level with `mode: full-refresh`, but when I try to run the replication it errors out with `Could not set column keys could not set update key. Did not find column update_dt`, as if Sling still tried to find the `update_key` in the source table.

If I remove the defaults and set everything on the stream level the full-refresh replications work without setting the primary and update key. 

This might be the expected behaviour as I set `primary_key` and `update_key` on the default level after all, so they should be in every stream source, but this prevents flexibly overriding the incremental mode on stream level (I could also leave the keys out of the defaults section, but that still results in lots of duplication across streams).

I would expect the stream to ignore the primary and update keys if mode is set to full-refresh.

- Sling version (`sling --version`): 

1.2.9

- Operating System (`linux`, `mac`, `windows`):  Linux in Docker on Mac

- Replication Configuration: 

Can't fully share

```yaml
source: <source>
target: <target>
streams:
  ...
```

- Log Output (please run command with `-d`): 

```
[90m8:38PM[0m [32mINF[0m [9 / 16] running stream [redacted]
[90m8:38PM[0m [32mINF[0m connecting to source database (mysql)
[90m8:38PM[0m [32mINF[0m connecting to target database (postgres)
[90m8:38PM[0m [32mINF[0m reading from source database
[90m8:38PM[0m [32mINF[0m [31mexecution failed[0m
[90m8:38PM[0m [32mINF[0m [31m~ Could not set column keys
could not set update key. Did not find column update_dt[0m

```

**Comment by flarco** [comment]
Hi, in those streams that you are overriding the default, can you try overriding the `primary_key` and `update_key` as well?

**Comment by somiandras** [comment]
Sorry for the late response here. "Clearing" the `primary_key` and `update_key` doesn't seem to work for me, I still get `Could not set column keys could not set update key. Did not find column update_dt` even after adding `update_key: null` to the stream config.

**Comment by flarco** [comment]
OK, will take a closer look.

**Comment by flarco** [comment]
Done. Should work in upcoming release in https://github.com/slingdata-io/sling-cli/pull/289.
Thanks for reporting.
