### ISSUE TITLE
Column Casing

### ISSUE THREAD

**Issue by gu-xie** [slingdata-io/sling-cli#34]
Sling CLI currently migrates data with column names as is from the source.

Ideally, we should have a configuration option to specific whether we want to force the column names to be all `upper-case` or `lower-case`.

This would make it easier to use on databases like Snowflake, where upper-case is the default and thus we don't need to wrap the column name in quotes when querying.

**Comment by flarco** [comment]
Nice. I dislike having to use the quotes as well 😄 .

Here is a rough concept:
```go
// ColumnCasing is the casing method to use
type ColumnCasing string

const (
	OriginalColumnCasing ColumnCasing = "original" // keeps original column name. The default.
	LowerColumnCasing    ColumnCasing = "lower"    // lower cases the names
	UpperColumnCasing    ColumnCasing = "upper"    // upper cases the names
	TargetColumnCasing   ColumnCasing = "target"   // cases the names according to target database
)
```

`original` would be the default, to keep things the way they are. I think `target` is what people would look for, since it's just automatic. Another thought is, should camel-cased names become-snake case names (`firstName -> first_name`) when choosing a non-`original` casing?

**Comment by gu-xie** [comment]
I love this concept @flarco ! Would also like that ability to convert snake-case to camel :)

**Comment by flarco** [comment]
Done.
Settled on this:

```go
// ColumnCasing is the casing method to use
type ColumnCasing string

const (
	SourceColumnCasing ColumnCasing = "source" // keeps source column name casing. The default.
	TargetColumnCasing ColumnCasing = "target" // converts casing according to target database. Lower-case for files.
	SnakeColumnCasing  ColumnCasing = "snake"  // converts snake casing according to target database. Lower-case for files.
)
```
You can specify with `target.options.column_casing: source | target | snake`
Docs: https://docs.slingdata.io/sling-cli/running-tasks#target-options-tgt-options-flag-target.options-key
Commit: https://github.com/slingdata-io/sling-cli/pull/38/commits/0546848f9e308326e1f242ee20ec69a6d8793f03
Please try with `1.0.50`.
