### ISSUE TITLE
index is not a valid table key type?

### ISSUE THREAD

**Issue by isaacrlee** [slingdata-io/sling-cli#342]
## Issue Description

- Description of the issue: 
  - `index` does not seem like a valid type for `table_keys`. I think it might be missing [here](https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/iop/datatype.go#L85)? I found the `table_keys` feature through [this issue](https://github.com/slingdata-io/sling-cli/issues/149#issuecomment-1936395489) where `index` is an example.

- Sling version (`sling --version`): I am using 1.1.5, but I don't think there have been changes since the table keys feature was added in 1.1.4.

- Operating System (`linux`, `mac`, `windows`): Windows

- Replication Configuration: 
I am using a dictionary for config through integration with Dagster but the relevant config is:
```
 "target_options": {
      "table_keys": {
          "index": ["column_to_index"],
      },
  }
```
          

- Log Output (please run command with `-d`): 

```
index is not a valid table key type. Valid table key types are: "aggregate","cluster","duplicate","hash","partition","primary","sort","unique","update"
```

**Comment by flarco** [comment]
Hi, first thing, you are using an ancient version of sling. Would be good to upgrade for more features and stability.
Second, you are right, the index is actually missing for the list here: https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/iop/datatype.go#L85
This will be added in the next release, however in the issue (https://github.com/slingdata-io/sling-cli/issues/149#issuecomment-1936395489) you've linked, this was an example of what the future would look like. Those don't work yet.
There is this outstanding issue open for that work: https://github.com/slingdata-io/sling-cli/issues/226

**Comment by isaacrlee** [comment]
Thanks for the response, apologies, was skimming through issues and missed the part about it being planned. Feel free to close this as a duplicate of 226.

**Comment by flarco** [comment]
No worries, I'll add indexes for next release, actually not a huge lift.

**Comment by flarco** [comment]
Fixed in https://github.com/slingdata-io/sling-cli/pull/344
