### ISSUE TITLE
BigQuery UTF encoding and transforms being ignored.

### ISSUE THREAD

**Issue by ravenscroftj** [slingdata-io/sling-cli#347]
## Issue Description

- Description of the issue: 

- Sling version (`sling --version`):  Version: 1.2.14

- Operating System (`linux`, `mac`, `windows`):  `mac`

- Replication Configuration: 

```yaml
source: MYSQL
#target: GOOGLE_STORAGE
target: BIGQUERY
#target: LOCAL



defaults:
  object: "{stream_schema}.{stream_table}"
  mode: full-refresh
  target_options:
  #   format: jsonlines
     compression: gzip

  # all tables in schema, except "forbidden_table"
  mydbname.articles:
    mode: incremental
    primary_key: [id]
    source_options:
      transforms:
        - replace_non_printable
        - replace_0x00
        - encode_utf8
    target_options:
      transform:
        - replace_non_printable
        - replace_0x00
        - encode_utf8
        - encode_windows1250
    select:
      - -html
      - -content
      - -url_hash_bin
```
- Log Output (please run command with `-d`): 

```
--- database_bigquery.go:592 func3 ---
~ Error copying from /var/folders/mx/3yp8d39d5kb83gw7sh8z4bfh0000gn/T/bigquery/<dbname>.articles/2024-07-29T120256.690/part.01.0001.csv.gz into <dbname>.`articles_tmp`
--- database_bigquery.go:711 CopyFromLocal ---
~ Error in Import Task
--- database_bigquery.go:745 LoadCSVFromReader ---
{Location: ""; Message: "Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 6; errors: 2; max bad: 0; error percent: 0"; Reason: "invalid"}

--- task_run.go:99 func1 ---
--- task_run.go:553 runDbToDb ---
~ Could not WriteToDb
--- task_run_write.go:317 WriteToDb ---
~ could not insert into `<dbname>`.`articles_tmp`
--- database_bigquery.go:538 BulkImportFlow ---
~ Error importing to BigQuery
--- database_bigquery.go:612 importViaLocalStorage ---

--- database_bigquery.go:592 func3 ---
~ Error copying from /var/folders/mx/3yp8d39d5kb83gw7sh8z4bfh0000gn/T/bigquery/`<dbname>`.`articles_tmp`/2024-07-29T120256.690/part.01.0001.csv.gz into `<dbname>`.`articles_tmp`
--- database_bigquery.go:711 CopyFromLocal ---
~ Error in Import Task
--- database_bigquery.go:745 LoadCSVFromReader ---
{Location: ""; Message: "Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 6; errors: 2; max bad: 0; error percent: 0"; Reason: "invalid"}
```

And when I inspect the bigquery job log:

```
Error encountered during job execution:
Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 6; errors: 2; max bad: 0; error percent: 0
Failure details:
 - Error while reading data, error message: Bad character (ASCII 0)
   encountered.; line_number: 8 byte_offset_to_start_of_line: 2307
   column_index: 3 column_name: "summary" column_type: STRING value:
   "Co mnie bardzo za..."
 - Error while reading data, error message: Bad character (ASCII 0)
   encountered.; line_number: 9 byte_offset_to_start_of_line: 2776
   column_index: 3 column_name: "summary" column_type: STRING value:
   "James Cowen joins..."
```

We have some extended non utf-8 characters in this table and I can't easily change that so I need sling to clean the data up. I assumed that setting transforms would do that.

## Solution (I think)

Deep diving into the codebase in the bigquery file on lines [567](https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/database/database_bigquery.go#L567) and [652](https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/database/database_bigquery.go#L652) I noticed that there are some data flow writes being done where a default config is passed rather than `nil` and this overrides my transforms.

If I recompile with these both set to `nil` instead of `iop.DefaultStreamConfig()` the sync works. I was going to submit a PR but I wanted to check to see if there is a reason that this is being done or if it was a mistake.

Thanks

**Comment by flarco** [comment]
Interesting, thanks for raising. This was done in this [commit](https://github.com/slingdata-io/sling-cli/commit/a1ef7ce9729a4791bff30cd935594779993b870e#diff-be034597e474ede11ddc490fbb3a6ee8190d36c49d2a056f600e90d6aecfd989) because, for example, the delimiter setting would be carried through, messing with the BigQuery hard coded import settings [here](https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/database/database_bigquery.go#L770-L774). Similarly applies to Snowflake, SQL Server and StarRocks as well. But you're right, the transforms should be left alone. Let me think about a proper solution.
BTW, `transforms` don't apply to `target_options`, only `source_options`, so sling ignores that.

**Comment by ravenscroftj** [comment]
Ah yeah that makes sense - thank you. I thought the transform didn't apply to target_options but I tried adding it in desperation when I noticed that the transforms were not being applied 😄 

I'm running my workflow with my forked version of the tool for now but would love to know if and when you find a better solution thank you!

**Comment by flarco** [comment]
Pushed this fix: https://github.com/slingdata-io/sling-cli/pull/344/commits/d4a94b94c8234abddae79bada46f48757d06beea
Do you mind testing out [this branch](https://github.com/slingdata-io/sling-cli/pull/344)?

**Comment by ravenscroftj** [comment]
This seems to work well now, thank you very much :)
