### ISSUE TITLE
Starrocks column separator for stream load

### ISSUE THREAD

**Issue by janlink** [slingdata-io/sling-cli#354]
## Feature Description

I want to insert data into Starrocks using Sling. 
I now have the problem that the fields in the source contain values that include a comma. 
However, the column separator in the Starrocks stream load is hardcoded to a comma.
 https://github.com/slingdata-io/sling-cli/blob/b9be42ed0bb4c51ad4c45bda2ef8240775bec821/core/dbio/database/database_starrocks.go#L452
This causes issues when inserting the data.
https://docs.starrocks.io/docs/sql-reference/sql-statements/data-manipulation/STREAM_LOAD/#csv-parameters
Is there any way to set the column separator myself or does this has to be added to sling?

Thanks
Jan

**Comment by flarco** [comment]
Interesting, that should work since cell values including a comma would be enclosed with a `"`, can you try `format: json` in your env.yaml starrocks connection ? It'll be slower, but should work.

**Comment by janlink** [comment]
Yes, that's correct. I was on the wrong track there.

However, I'm having difficulties debugging the result because after a failed run, the temporary tables and files are removed.

Is there an option to somehow keep them for debugging purposes?

**Comment by flarco** [comment]
I just added `KEEP_TEMP_FILES` here: https://github.com/slingdata-io/sling-cli/pull/344/commits/65a6119b09ad15e84f387d9f3ea028cb6b97b4be

If you build the binary on that branch, and pass env var `KEEP_TEMP_FILES=true`, it'll keep it

**Comment by janlink** [comment]
Hi, thanks for the quick help. I have built the V1.2.15 branch.

However, when I now run a simple replication, I get the following vague error message.

Is there an issue with the state of this branch?


./sling run -d --src-conn my_source --src-stream 'SELECT xyz FROM my_table' --tgt-conn starrocks --tgt-object my_target_schema.my_table

2024-08-12 15:35:54 DBG Sling version: dev (linux amd64)
2024-08-12 15:35:54 DBG type is db-db
2024-08-12 15:35:54 DBG using source options: {"empty_as_null":false,"null_if":"NULL","datetime_format":"AUTO","max_decimals":-1}
2024-08-12 15:35:54 DBG using target options: {"datetime_format":"auto","file_max_rows":0,"max_decimals":-1,"use_bulk":true,"add_new_columns":true,"adjust_column_type":false,"column_casing":"source"}
2024-08-12 15:35:54 INF execution failed
fatal:
--- task_run.go:98 func1 ---
--- task_run.go:471 runDbToDb ---
--- task_run.go:152 getSrcDBConn ---
--- task.go:319 setGetMetadata ---
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
--- map_faststr.go:205 mapassign_faststr ---
--- panic.go:770 gopanic ---
--- task_run.go:74 1 ---
panic occurred! "assignment to entry in nil map"
goroutine 54 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/slingdata-io/sling-cli/core/sling.(*TaskExecution).Execute.func1.1()
        /home/jan/code/sling-cli/core/sling/task_run.go:74 +0x3d
panic({0x2f71420?, 0x3e470b0?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/slingdata-io/sling-cli/core/sling.(*TaskExecution).setGetMetadata(0xc0005b3b00)
        /home/jan/code/sling-cli/core/sling/task.go:319 +0x2f6
github.com/slingdata-io/sling-cli/core/sling.(*TaskExecution).getSrcDBConn(0xc0005b3b00, {0x3e7eb10, 0xc0010cacd0})
        /home/jan/code/sling-cli/core/sling/task_run.go:152 +0x3a
github.com/slingdata-io/sling-cli/core/sling.(*TaskExecution).runDbToDb(0xc0005b3b00)
        /home/jan/code/sling-cli/core/sling/task_run.go:471 +0xbb
github.com/slingdata-io/sling-cli/core/sling.(*TaskExecution).Execute.func1()
        /home/jan/code/sling-cli/core/sling/task_run.go:98 +0x3b9
created by github.com/slingdata-io/sling-cli/core/sling.(*TaskExecution).Execute in goroutine 1
        /home/jan/code/sling-cli/core/sling/task_run.go:67 +0x3b3

**Comment by flarco** [comment]
try now, this branch hasn't passed tests yet, so there may be bugs.

**Comment by janlink** [comment]
thanks for your help, now it is working and easier for me to debug!

**Comment by flarco** [comment]
Closing, feel free to re-open.
