### ISSUE TITLE
Incremental with update-key reinserting existing rows

### ISSUE THREAD

**Issue by guaripete-github** [slingdata-io/sling-cli#36]
Log 
```
DBG type is db-db
INF connecting to source database (azuresql)
INF connecting to target database (sqlserver)
INF getting checkpoint value
DBG select max("UpdateDate") as max_val from "rpt"."Location"
INF reading from source database
DBG select * from "rpt"."Location" where UpdateDate >= '2023-10-24 15:00:34.253'
```

task_run_read.go
```go
	if t.usingCheckpoint() {
		// select only records that have been modified after last max value
		incrementalWhereCond := "1=1"
		if cfg.IncrementalVal != "" {
			greaterThan := ">="
			if val := os.Getenv("SLING_GREATER_THAN_EQUAL"); val != "" {
				greaterThan = lo.Ternary(cast.ToBool(val), ">=", ">")
			}
			incrementalWhereCond = g.R(
				"{update_key} {gt} {value}",
				"update_key", cfg.Source.UpdateKey,
				"value", cfg.IncrementalVal,
				"gt", greaterThan,
			)
		}
```

Currently, the incrementalWhereCond is defined with operand `>=` instead of `>`. Overriding operand using environmental variable `SLING_GREATER_THAN_EQUAL = '>'` renders expected behavior.

**Comment by flarco** [comment]
Thanks, will change the default to `>`.

**Comment by guaripete-github** [comment]
Much appreciated.

Also, having similar issue with Database -> Database (Custom SQL) when using incremental with update-key. In this case, the entire table/stream gets re-added given the incrementalWhereCond is not applied. It could be worthwhile for the CLI to error when such task is attempted. Or maybe wrap the Custom SQL in a Common Table Expression (CTE) and have the final SQL statement include the incrementalWhereCond?

**Comment by flarco** [comment]
Done.
Add Docs for this: https://docs.slingdata.io/sling-cli/running-tasks#incremental-mode-with-custom-sql
Commit: https://github.com/slingdata-io/sling-cli/pull/38/commits/d59e78ccecf05ea676f06d2f6bb84ea7f9e47e8e
Please try with new version `1.0.50`.
