### ISSUE TITLE
Snowflake create _TMP table of type transient

### ISSUE THREAD

**Issue by TimPossiblee** [slingdata-io/sling-cli#360]
## Feature Description
Is there a way to create the _TMP table as transient in Snowflake?
It would be nice to have the option of transient or even temporary tables in Snowflake.
With normal tables there is always at least a Failsafe Period (7 days) where data is kept for disaster recovery.
IMO it makes sense to have the final table as "permanent" and the _TMP ones as transient.

https://docs.snowflake.com/en/user-guide/tables-temp-transient#comparison-of-table-types

**Comment by flarco** [comment]
Added in https://github.com/slingdata-io/sling-cli/pull/357.
Closing.
