### ISSUE TITLE
delimiterRep $~d$~ in bcp import

### ISSUE THREAD

**Issue by guaripete-github** [slingdata-io/sling-cli#368]
## Issue Description

- Description of the issue: seems like the delimiterRep `$~d$~` is not replaced back to commas before bcp import command step

- Sling version (`sling --version`): 1.2.17

- Operating System (`linux`, `mac`, `windows`):  linux, windows

For example:

`(CHECKS, EFT, DIRECT PAY, ETC)`

shows as

`(CHECKS$~d$~ EFT$~d$~ DIRECT PAY$~d$~ ETC)`

**Comment by flarco** [comment]
Thanks, will fix.

**Comment by flarco** [comment]
@guaripete-github I can't reproduce, my test is working. Can you run it with `DEBUG=TRACE` to see if the update statement gets called?

`UPDATE "dbo"."test1k_sqlserver_bcp_tmp" SET first_name = REPLACE(REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(MAX), first_name), '$~d$~', ','), '$~q$~', '"'), '$~r$~', CHAR(13)), '$~n$~', CHAR(10)), last_name = REPLACE(REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(MAX), last_name), '$~d$~', ','), '$~q$~', '"'), '$~r$~', CHAR(13)), '$~n$~', CHAR(10))`

**Comment by flarco** [comment]
happening here: https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/database/database_sqlserver.go#L354-L400

**Comment by guaripete-github** [comment]
I see.

I have a table_ddl and the replication hits a truncation error given by the added characters. Therefore, not getting to the update statement.

I can work around by increasing the length of the column in table_ddl.

Thanks for looking into it.

**Comment by flarco** [comment]
Cool.
