### ISSUE TITLE
trino limit offset errors

### ISSUE THREAD

**Issue by metalshanked** [slingdata-io/sling-cli#371]
## Issue Description

- Description of the issue: 

Sling generates invalid SQL for trino.  i.e. it has LIMIT followed by OFFSET.
Manually adjusting the generated query by re-ordering OFFSET and the LIMIT seems to work

```
-- generated by sling / does not work
select * from (
  select a,b,c from my.trino.table
) as t limit 1 offset 0
 /* GetSQLColumns */  /* nD */
 ```

```
-- manually updated offset and limit position / works
select * from (
  select a,b,c from my.trino.table
) as t offset 0 limit 1 
 /* GetSQLColumns */  /* nD */
 ```

- Sling version (`sling --version`):  1.2.18

- Operating System (`linux`, `mac`, `windows`): windows

- Replication Configuration: 

```yaml
source: TRINO
target: LOCAL
streams:
  sql_query
```

- Log Output (please run command with `-d`): 

```
3:45PM INF execution failed
trino: query failed (200 OK): "USER_ERROR: line 3:16: mismatched input 'offset'. Expecting: <EOF>"
```

**Comment by flarco** [comment]
Thanks, fixed [here](https://github.com/slingdata-io/sling-cli/pull/370/commits/4320398cf58918b37f86febdc01a1618a778d437).
