### ISSUE TITLE
MongoDB _id fields are not extracted correctly when they aren't the first field in the document

### ISSUE THREAD

**Issue by hmac** [slingdata-io/sling-cli#377]
I have some MongoDB collections with a `__v` field which is lexicographically lesser than `_id`. For those collections, sling seems to extract `_id` incorrectly, giving it same value as `__v`.

I think this is due to the line below, where `Row[0]` should be `Row[i]`?

https://github.com/slingdata-io/sling-cli/blob/0a3f82b845d76d062875a0d62d1fe38da632febf/core/dbio/database/database_mongo.go#L248

**Comment by flarco** [comment]
Thanks for reporting. 
[Fixed](https://github.com/slingdata-io/sling-cli/pull/370/commits/5e78ad3b0b04fd4a5612754a0cbb3fb7d4bae418)..
