### ISSUE TITLE
error with sqlldr

### ISSUE THREAD

**Issue by giorgiotobia** [slingdata-io/sling-cli#388]
## Issue Description

- Description of the issue: 
I'm trying to use an oracle target with sqlldr.
but sling exit with the error "Oracle Import Error:LRM-00112: multiple values not allowed for parameter 'control'"

i tried to reproduce the issue running sqlldr by myself and i've understood the the issue is
a password containing special characters ( "[,+]" as example ) that cause the program to break 
to make it work i should enclose the conn credentials between escaped "'"
\\'user:password@host:port/service_name\\'

- Sling version (`sling --version`): 
1.2.20
- Operating System (`linux`, `mac`, `windows`): 
linux
- Replication Configuration: 
none

- Log Output (please run command with `-d`): 

```
fatal:
--- proc.go:271 main ---
--- sling_cli.go:458 main ---
--- sling_cli.go:494 cliInit ---
--- cli.go:286 CliProcess ---
--- sling_run.go:225 processRun ---
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
--- sling_run.go:396 runTask ---
--- task_run.go:138 Execute ---

--- task_run.go:99 func1 ---
--- task_run.go:543 runDbToDb ---
--- task_run_write.go:331 WriteToDb ---
--- database.go:2313 BulkImportFlow ---
~ could not bulk import
--- database.go:2300 func1 ---
~ Error with SQLLoad
--- database_oracle.go:256 BulkImportStream ---
~ Oracle Import Command:
sqlldr **** control=/tmp/oracle.data.sqlldr.1727340128739.9pv.ctl discardmax=0 errors=0 data=/dev/stdin log=/dev/stdout bad=/dev/stdout

... cut

Oracle Import Error:LRM-00112: multiple values not allowed for parameter 'control'

SQL*Loader: Release 19.0.0.0.0 - Production on Thu Sep 26 08:42:08 2024
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle and/or its affiliates.  All rights reserved.

SQL*Loader-100: Syntax error on command-line


--- database_oracle.go:361 SQLLoad ---
exit status 1

--- task_run.go:99 func1 ---
~ Could not WriteToDb
--- task_run.go:543 runDbToDb ---
~ could not insert into "schema"."table"
--- task_run_write.go:337 WriteToDb ---


```

**Comment by flarco** [comment]
The creds for the sqlldr command get constructed [here](https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/database/database_oracle.go#L301-L304).
Go should have escaped it as needed when submitting the command.
Does your password have a single quote (`'`) or double (`"`)?

**Comment by giorgiotobia** [comment]
Hi

i tried with
password without quotes
password quoted between ( ' )
password quoted between ( " )
without results

**Comment by flarco** [comment]
try this: https://stackoverflow.com/a/6496094/2295355

**Comment by giorgiotobia** [comment]
1:15PM INF execution failed
fatal:
~ could not connect to database
ORA-01017: invalid username/password; logon denied

**Comment by flarco** [comment]
I'll have to test on my side. For now, you can do `target_options.use_bulk = false` to not use `sqlldr`

**Comment by giorgiotobia** [comment]
Hi

it's raw but for me this works

	proc := exec.Command(
		"sqlldr",
		"'"+credHost+"'",
		"control="+ctlPath,
		"discardmax=0",
		"errors=0",
		"data="+dataPath,
		"log="+logPath,
		"bad="+logPath,
	)

**Comment by flarco** [comment]
Not raw. Thanks, i'll push this to next release.

**Comment by giorgiotobia** [comment]
thank you :-)
