### ISSUE TITLE
csv enhance: support quote customized(single quote/double quote/ empty)

### ISSUE THREAD

**Issue by yokofly** [slingdata-io/sling-cli#389]
## Feature Description

What would you like to see added to Sling?

the main idea is to support single quote in case some incorrect wording to make the parse fail.
sample:
how,are,you => 'how','are','you', => "how","are","you"

for a more general idea, I propose making this config as the delimiter configurable.

### duckdb:
https://duckdb.org/docs/data/csv/auto_detection.html#dialect-detection
https://github.com/slingdata-io/sling-cli/commit/731eedf78eaa33e221a64adebfdf6db12d6a0fb5#diff-f3ff074baed58efda6dfd6e158f3b4619ee3e8ee79fd7c4685847e11257b7861R65-R79

### another tooling in csv options
https://docs.pingcap.com/tidb/stable/dumpling-overview#option-list-of-dumpling:~:text=for%20TLS%20connection-,%2D%2Dcsv%2Ddelimiter,%22%5CN%22,-%2D%2Dcsv%2Dline%2Dterminator

**Comment by yokofly** [comment]
@flarco  Is this on your roadmap for the next release? If not, I can start working on this. Do you like this idea?

**Comment by flarco** [comment]
Interesting. Sure, PR would be welcome for this.
It shouldn't be hard, just follow the use of [`StreamConfig.Escape`](https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/iop/stream_processor.go#L56) and add `StreamConfig.Quote` everywhere it's used.
Also, a test in https://github.com/slingdata-io/sling-cli/blob/main/cmd/sling/tests/suite.cli.tsv would be great.

**Comment by yokofly** [comment]
thanks

**Comment by yokofly** [comment]
I have done something, but we can probably add another contribution guide later. 

Currently, the branch naming, ticket naming, commit info format, PR description template, code style, and local test running procedure I cannot found them.

I understand that maintaining this repository will require more effort, so this is just a suggestion, and we can put it later if the community has more stuff involved :p

**Comment by flarco** [comment]
Thanks, agreed. I need to work on a guide overall.

For testing, just make sure you have your connection name defined if you're using a DB. The [suite.cli.tsv](https://github.com/slingdata-io/sling-cli/blob/main/cmd/sling/tests/suite.cli.tsv) just runs the command as defined using the built binary. It can be multiple lines (or use ` && ` or `;`), as a temp bash script get [created and runs](https://github.com/slingdata-io/sling-cli/blob/main/cmd/sling/sling_cli_test.go). For your case, I'm thinking you can add a new test entry with a command like `sling run --src-stream file://cmd/sling/tests/files/test1.csv --tgt-options '{ quote: "''" }' --limit 10 --stdout` and test the output.

Then you can run individual tests like this:

```bash
bash scripts/build.sh  # build binary with changes
cd cmd/sling
cp ../../sling .
TESTS=49 SLING_BIN=./sling go test -v -run TestCLI # will run test 49 from suite.cli.tsv
TESTS=50-51 SLING_BIN=./sling go test -v -run TestCLI # will run test 50 to 51 from suite.cli.tsv
```

No need to run everything in `scripts/test.sh` as it requires over a dozen live connections.  Also, don't bother with the github automatic action runner.

**Comment by yokofly** [comment]
thanks. I am struggling with the final tsv quote display. :smiley: 
By the way, if you are current still in the US, it's better to go to bed for your health.

**Comment by flarco** [comment]
haha, i woke up unusually early this morning.

**Comment by flarco** [comment]
Added: https://github.com/slingdata-io/sling-cli/tree/1.2.21?tab=readme-ov-file#contributing

**Comment by flarco** [comment]
Closing.
