### ISSUE TITLE
Use Correct BCP Field/Line Terminators

### ISSUE THREAD

**Issue by flarco** [slingdata-io/sling-cli#39]
Links
- https://learn.microsoft.com/en-us/sql/relational-databases/import-export/specify-field-and-row-terminators-sql-server?view=sql-server-ver16#characters-supported-as-terminators
- https://learn.microsoft.com/en-us/sql/relational-databases/import-export/use-character-format-to-import-or-export-data-sql-server?view=sql-server-ver16#considerations-for-using-character-format

See https://github.com/slingdata-io/sling-cli/issues/19#issuecomment-1783574600

**Comment by guaripete-github** [comment]
FYI  [The weird case of bcp and Unix line endings](https://vladdba.com/2024/05/09/bcp-unix-line-endings/)
