### ISSUE TITLE
BigQuery Database Connection Ignores Specified Location for New Datasets

### ISSUE THREAD

**Issue by Faegru-dw** [slingdata-io/sling-cli#392]
### Context
As stated in the [documentation](https://docs.slingdata.io/connections/database-connections/bigquery), one of the accepted keys for a connection to a BigQuery (BQ) database is the `location`.

### Issue
When performing an extraction to a **new** dataset and table, both are created in the default location (`US`), regardless of the specified `location` value. Upon reviewing the code, it seems that the `location` parameter is not being applied during the [initialization](https://github.com/slingdata-io/sling-cli/blob/2b4c938390d9eb3556ee4adb3442478c8e439c14/core/dbio/database/database_bigquery.go#L46). It must be noted that the problem is only visible when the dataset doesn't exist; otherwise, it appears to [retrieve the location from the dataset's metadata](https://github.com/slingdata-io/sling-cli/blob/2b4c938390d9eb3556ee4adb3442478c8e439c14/core/dbio/database/database_bigquery.go#L1073).

### Version
- Sling version (`sling --version`): `1.2.20`

- Operating System (`linux`, `mac`, `windows`): `linux`

**Comment by flarco** [comment]
Thanks, pushed this [commit](https://github.com/slingdata-io/sling-cli/pull/390/commits/7c17e5160439cdebd8ebc2d8293ec7565292163d). Can you the latest dev-build?
https://github.com/slingdata-io/sling-cli/tree/1.2.21?tab=readme-ov-file#automated-dev-builds

**Comment by Faegru-dw** [comment]
@flarco Thank you for your quick response! I've tried the new version, and while `conn.Location` is now correctly set, the dataset is still being created in the `US`. I wasn't able to find exactly where the dataset is created when it's not already in the database, so I'm not able to propose any changes for the moment. :(

**Comment by flarco** [comment]
Pushed new [changes](https://github.com/slingdata-io/sling-cli/pull/390/commits/c559bcba99042f7e7acb73e1ef4e930df69585dd), can you try again with latest build?

**Comment by Faegru-dw** [comment]
@flarco thanks again for the quick response! I tried the new version and:

- The correct location is now being set when creating the table.
- However, the dataset is still being created in the US before anything else.

As a result, it fails when writing the table because it tries to find the dataset in the EU, but the dataset was created in the US.

Fortunately, this time, I do have some feedback to share! :) [In this section](https://github.com/slingdata-io/sling-cli/blob/2933c36e0ffe0fd0d43849b8379bf91af5c27b52/core/dbio/database/database_bigquery.go#L233-L238), it passes a default dataset that gets created with a new session because `CreateSession: true` is being used. Based on the [documentation](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfigurationQuery.FIELDS.connection_properties:~:text=the%20query%20behavior.-,createSession,it%27s%20set%20to%20the%20default%20location%20based%20on%20existing%20routing%20logic.,-systemVariables), it looks like the session location could be set to the US by default in this case.

As a way to work around this issue, I found that you can include `q.JobIDConfig.Location = conn.Location` to ensure the session is created in the correct location. So, by replacing [this](https://github.com/slingdata-io/sling-cli/blob/2933c36e0ffe0fd0d43849b8379bf91af5c27b52/core/dbio/database/database_bigquery.go#L233-L238) with:
```
q := conn.Client.Query(sql)
q.JobIDConfig.Location = conn.Location
q.QueryConfig = bigquery.QueryConfig{
	Q:                sql,
	DefaultDatasetID: conn.GetProp("schema"),
	CreateSession:    true,
}
```
This extra line makes sure the session and jobs run in the intended location. After adding this change, everything is working correctly!

**Comment by flarco** [comment]
Pushed. Thank you for the snippet.
Closing.
