### ISSUE TITLE
Parameterize connection settings in replication.yaml.

### ISSUE THREAD

**Issue by dvdrndlph** [slingdata-io/sling-cli#396]
## Issue Description
- Description of the issue: 
The documentation implies I can access a connection's schema setting in a replication.yaml file:

```
source: MY_MYSQL
target: MY_BIGQUERY

defaults:
  mode: incremental
  object: {target_schema}.{stream_schema}_{stream_table}
  primary_key: [id]
```
But {target_schema} does not get populated with the schema name from env.yaml. 

It is inconvenient to have to hard-code the target schema.

- Sling version (`sling --version`): 
Version: 1.2.20

- Operating System (`linux`, `mac`, `windows`): 
Windows, Linux

- Replication Configuration: 

As above.

- Log Output (please run command with `-d`): 

```
fatal:
--- proc.go:271 main ---
--- sling_cli.go:458 main ---
--- sling_cli.go:494 cliInit ---
--- cli.go:286 CliProcess ---
--- sling_run.go:200 processRun ---
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
--- sling_run.go:438 runReplication ---
~ Error parsing replication config
--- replication.go:767 LoadReplicationConfigFromFile ---
~ Error parsing replication config
--- replication.go:779 LoadReplicationConfig ---
~ Error parsing yaml content
--- replication.go:585 UnmarshalReplication ---
yaml: line 3: mapping values are not allowed in this context
```
Many thanks.

**Comment by flarco** [comment]
hey @dvdrndlph in your connection entry in the `env.yaml`, are you specifying a `schema` key?

**Comment by dvdrndlph** [comment]
Yes, here is the stanza:
```
  ORABOODLE:
    type: oracle
    host: db-test.foo.uic.edu
    user: TST_CDW
    port: 1527
    service_name: OLD.foo.uic.edu
    schema: TST_CDW
    password: ***
```

**Comment by dvdrndlph** [comment]
My env.yaml starts like this:
```
source: CDW_MSSQL
target: ORABOODLE

defaults:
  mode: incremental
  object: {target_schema}.{stream_table}
  update_key: _LastUpdatedInstant

streams:
  AddressHistoryFact:
    primary_key: AddressHistoryKey
.
.
.
```
I have to hard code `TST_CDW` in lieu of `{target_schema}` to run the replication.

**Comment by flarco** [comment]
ok, just tested, you just need to add quotes:  `'{target_schema}.{stream_table}'`, YAML actually doesn't like the base curly brackets (it thinks it's a map). Closing.
