### ISSUE TITLE
rudder error

### ISSUE THREAD

**Issue by maxlivi** [slingdata-io/sling-cli#4]
Hello,
First thanks a lot  for sling !

I am getting the following  errors on the log:

9:34AM INF connecting to target database (postgres)
9:34AM INF reading from source file system (file)
9:34AM INF writing to target database [mode: truncate]
9:34AM INF streaming data
1s 27,369 ? p/s  2s 86,156 58791 r/s  3s 149,002 59052 r/s  3s 208,232 73492 r/s  9:34AM INF truncated table public.wh2a
9:34AM INF inserted 257893 rows in 24 secs [10,544 r/s]
9:34AM INF execution succeeded
rudder 2023/08/19 09:34:30 **INFO**: response 401 401 Unauthorized – Failed to read writeKey from header
rudder 2023/08/19 09:34:30 **ERROR**: 1 messages dropped because they failed to be sent and the client was closed

It seems that they started after version  0.87.90.

Apart the error on the log everything seems fine.

DB is postgres + Timescale

Cheers 

Max

**Comment by flarco** [comment]
Hey Max, no problem!
I just released a new version to fix this logging. Feel free to update to 1.0.3.
I'll close this issue, let me know if anything else.
