### ISSUE TITLE
MSSQL BCP copy fails when using TrustedConnection

### ISSUE THREAD

**Issue by pSpitzner** [slingdata-io/sling-cli#402]
- Description of the issue:
  -  When running a copy into MSSQL via TrustedConnection with `bulk_copy` (i.e. using the bcp driver), the copy fails due to login problems.
  -  When running the same copy to parquet instead, it works. Same when not using bulk copy.
  - I am sure the issue is caused by the parsing we do to create the bcp command. (see log below). We currenlty pass a `-U '' -P ''` but [according to the docs](https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16&tabs=windows#-t), trusted authentication needs a `-T`  _instead_ of the username and password combination.
  -  I could work on a PR if someone points me to the right code section (new to go)

- Sling version (`sling --version`): Version: 1.2.20

- Operating System: `windows` 

- Replication Configuration: 
```bash
sling run --src-conn db_source --src-stream 'dbo.source' --tgt-conn db_target --tgt-object 'raw.target'
```

- Conns Configuration:

```yaml
connections:
  db_target:
    type: sqlserver
    url: sqlserver://ip:port/?database=db_target&TrustServerCertificate=true&TrustedConnection=true
  
  db_source:
    type: sqlserver
    url: sqlserver://user:pass@server:port/?database=db_source&TrustServerCertificate=true
```

- Log Output (please run command with `-d`): 

```
10:43AM INF connecting to source database (sqlserver)
10:43AM INF connecting to target database (sqlserver)
10:43AM INF reading from source database
10:43AM INF writing to target database [mode: full-refresh]
10:43AM INF streaming data
6s 134,456 28899 r/s 25 MB
10:43AM INF execution failed

If facing issues with Microsoft's BCP, try disabling Bulk Loading with `use_bulk=false`. See https://docs.slingdata.io/sling-cli/run/configuration#target

fatal:


~ could not bulk import
~ SQL Server BCP Import Command -> bcp 'raw.target_tmp' in 'C:/Users/paul/AppData/Local/Temp/2/sqlserver.1728895390912.deM1.csv' -S '****' -d 'db_target' -t ',' -m '1' '-w' -q -b '50000'
 -F '2' -e 'C:/Users/paul/AppData/Local/Temp/2/sqlserver.1728895397124.15p.error' -U '' -P ''
SQL Server BCP Import Error  -> 
SQLState = 28000, NativeError = 18456
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Fehler bei der Anmeldung f�r den Benutzer "".

exit status 1

~ could not insert into "raw"."target_tmp"
~ SQL Server BCP Import Command -> bcp 'raw.target_tmp' in 'C:/Users/paul/AppData/Local/Temp/2/sqlserver.1728895390912.deM1.csv' -S '****' -d 'db_target' -t ',' -m '1' '-w' -q -b '50000'
 -F '2' -e 'C:/Users/paul/AppData/Local/Temp/2/sqlserver.1728895397124.15p.error' -U '' -P ''
SQL Server BCP Import Error  -> 
SQLState = 28000, NativeError = 18456
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Fehler bei der Anmeldung f�r den Benutzer "".
```

**Comment by flarco** [comment]
Just pushed this [commit](https://github.com/slingdata-io/sling-cli/pull/390/commits/f644fa5af88e253aa2e8c647bd63beea8a7c7acf).
Can you try the latest [dev build](https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#automated-dev-builds)?

**Comment by pSpitzner** [comment]
Wow, @flarco, what a super fast fix!

Working like a charm now. Thanks!
