### ISSUE TITLE
Keep Temporary File after Replication

### ISSUE THREAD

**Issue by TimPossiblee** [slingdata-io/sling-cli#403]
## Feature Description
We have a replication setup from SQL-Server to Snowflake, where sometimes one of the streams may fail because of a ZSTD error e.g. 'Unknown frame descriptor' or 'Data corruption detected'.
When we manually retry everything works again.
Because I'm not sure where the problem lies, I would like to compare the temporary file between sling runs.

It would be nice to have the option to keep the temp file around either when a stream errors or when manually debugging.

**Comment by flarco** [comment]
[Here](https://docs.slingdata.io/sling-cli/run/configuration/variables#global-environment-variables) you go:

<img width="743" alt="image" src="https://github.com/user-attachments/assets/180bc9ef-af79-4dd4-b68c-d9d0e8a4f135">

**Comment by TimPossiblee** [comment]
Ahh, thank you very much
