### ISSUE TITLE
All output on stderr

### ISSUE THREAD

**Issue by skostrewa** [slingdata-io/sling-cli#424]
## Issue Description

- Description of the issue: The logs produced from sling are printed to `stderr` instead of `stdout`. I witnessed this behaviour when integrating sling into a hop-project. I also tried wrapping sling into a python-script to check if it is a issue with hop, but the behaviour persisted. 

- Sling version (`sling --version`): 
1.2.23.dev (2024-10-28)
- Operating System (`linux`, `mac`, `windows`): 
Windows 11
- Replication Configuration: 
No Replication necessary. `sling --h` or `sling --version`

**Comment by flarco** [comment]
Hi, this is by design. Sling has a `--stdout` flag, which outputs the  actual data only to STDOUT, keeping the log output into STDERR. This will not be changed. You'll have to put some logic into your wrapper to capture from STDERR.
