### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by jakubbujny** [slingdata-io/sling-cli#428]
I have a problem to build that project from the source code. I found you provide some build script: https://github.com/slingdata-io/sling-cli/blob/main/scripts/build.sh 

it looks incorrect from Go perspective - why some dependencies are dropped in script? If they can be dropped why are they in go.mod at all?

**Comment by yokofly** [comment]
I have the same question, but I cannot understand as well.

I previously wrote in Rust. If the dependency changes, we can commit to a new fixed version.

**Comment by flarco** [comment]
Ah yes, it's because there are some internal files that are linked to a private repo (github.com/slingdata-io/sling), and it is more convenient for me to develop on the overall codebase this way.

**Comment by jakubbujny** [comment]
@flarco do you mean Sling is not fully open source?
Also have you ever investigated Go workspaces? https://go.dev/doc/tutorial/workspaces it basically solves your problem without leaving some development stuff in "production" go.mod
