### ISSUE TITLE
Is Sling fully open-source? 

### ISSUE THREAD

**Issue by jakubbujny** [slingdata-io/sling-cli#430]
In go.mod there is reference to the repository which seems to be private: https://github.com/slingdata-io/sling-cli/blob/091ea49d6c5172df24e1065289fda5c5daf7305d/go.mod#L57 

does it mean Sling is not fully open-source tool?

**Comment by flarco** [comment]
I guess you could call it open-core? 98% open-source?
There are some exciting upcoming features that will be closed-source (as a commercial offering).
What is free/open today will remain open/free (+more in future), and compilable on anyone's machine.
Let me know if you have any questions. Closing.
