### ISSUE TITLE
Use function as update key?

### ISSUE THREAD

**Issue by ArcqStrato** [slingdata-io/sling-cli#431]
I am trying to use a function as the update key, but that doesn't work.

I run Sling with these parameters to load data from Oracle:
```
--mode incremental \
--primary-key 'ID' \
--update-key 'COALESCE(MDATUM,EDATUM)' \
```

But Sling puts quotation marks around the update key. 
```
fatal:
~ SQL Error for:
select max("COALESCE(MDATUM,EDATUM)") as max_val from "MY_SCHEMA"."MY_TABLE"
000904 (42000): SQL compilation error: error line 1 at position 11
invalid identifier '"COALESCE(MDATUM,EDATUM)"'
```

This works fine as long as the update key is a column name, but fails if it is a function.

Is there a way to achieve this?

**Comment by flarco** [comment]
Hey, you should use a custom SQL for this, and use the aliased column as the `update_key`. Sling handles incremental for sql queries, see:
- https://docs.slingdata.io/sling-cli/run/configuration#incremental-or-backfill-mode-with-custom-sql

**Comment by ArcqStrato** [comment]
I ended up creating a view with an extra column (COALESCE(MDATUM,EDATUM) as EMDATUM) and slinging that view - but your solution would have been slicker, thanks!
