### ISSUE TITLE
MySQL automatic handling of unsigned fields

### ISSUE THREAD

**Issue by ravenscroftj** [slingdata-io/sling-cli#433]
## Issue Description

- Description of the issue: 
When working with MySQL tables containing unsigned fields, sling always fails to automatically map the data type to a known general type. For example:

```
2024-11-05 16:55:02 DBG using text since type 'unsigned int' not mapped for col 'id'
2024-11-05 16:55:02 DBG using text since type 'unsigned int' not mapped for col 'user_id'
2024-11-05 16:55:02 DBG using text since type 'unsigned int' not mapped for col 'company_id'
2024-11-05 16:55:02 DBG using text since type 'unsigned int' not mapped for col 'created_by_user'
```

I would expect that sling could either support unsigned data types or a simpler solution would be to throw away the "unsigned " prefix and just map int to integer.

I noticed that the NativeTypeToGeneral function has some code for dealing with specific databases and cleaning up non standard data types so perhaps an additional check could be added here for MySQL? I'm happy to submit a PR for this if that solution sounds ok.

- Sling version (`sling --version`): 

Version: 1.2.22

- Operating System (`linux`, `mac`, `windows`): 

Linux + Mac

**Comment by flarco** [comment]
Done, added in latest dev build: https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#automated-dev-builds
Closing.

**Comment by ravenscroftj** [comment]
Sorry for slow follow up - this has worked, thank you very much!
