### ISSUE TITLE
No error when connection is lost

### ISSUE THREAD

**Issue by arrafik** [slingdata-io/sling-cli#438]
## Issue Description

- Description of the issue: 
Hello,
when I lose the connection to my source database, I do not get any error reported.
The sling tool tells me that the processing went well even though it did not recover the entire table.
How can I get the error ?

- Sling version (`sling --version`): 
1.2.20

- Operating System (`linux`, `mac`, `windows`): 
Windows 10 professional

- Replication Configuration: 

source: MSSQL
target: CRMDS_FTP

defaults:
  mode: full-refresh

streams:
  dbo.F_LIGNE_TICKET_SKU:
    sql: |
      select * FROM dbo.F_LIGNE_TICKET_SKU
    object: SLING.F_LIGNE_TICKET_SKU

- Log Output (please run command with `-d`):

**Comment by flarco** [comment]
Similar to https://github.com/slingdata-io/sling-cli/discussions/407.
I will try to reproduce.

**Comment by arrafik** [comment]
Ok, Don't hesitate to send me a message if you can't reproduce.
Thanks for your help

**Comment by flarco** [comment]
I pushed a fix. Can you try with the latest [dev build](https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#automated-dev-builds)?

**Comment by flarco** [comment]
This is fixed, closing.
