### ISSUE TITLE
Issue Loading chinese characters from Snowflake to SQL Server

### ISSUE THREAD

**Issue by kkprab** [slingdata-io/sling-cli#443]
I am trying to load data from Snowflake to SQL Server 
In SQL Server column value with chinease characters transformed to ???? (question marks)

Sample below
![image](https://github.com/user-attachments/assets/ad41dc28-863f-41fd-a298-07aa68258217)

in Snowflake we see the charaters
![image](https://github.com/user-attachments/assets/1bb161ab-2a11-4ea6-9d0b-fb35185e479e)

in config file i have tried with encode or decode UTF8 but no success
![image](https://github.com/user-attachments/assets/e59da8d2-584e-4eab-81eb-d40e209b2f53)

Can you plz suggest what configuration we try

**Comment by flarco** [comment]
A few questions:
- What version of sling are you using?
- Are you loading into SQL Server with bcp?
  - if so, can you try without bulk (`target_options: { use_bulk: false }`).
- can you try the cli to stdout to see if the characters show OK? `sling run --src-conn core_dev --src-stream dev.table --limit 10 --stdout`

**Comment by kkprab** [comment]
Thanks Flarco
- Using sling version 1.2.22
- Tried with use_bulk: false still showing ??? instead of chinese characters
- While running cli as you have suggested and i can see chinese characters in the output

![image](https://github.com/user-attachments/assets/f7de210a-68a7-4539-86a1-4804f9921e98)

**Comment by kkprab** [comment]
Update: The initial test was conducted on Linux. I installed Sling on Windows and repeated the test. This time, Chinese characters were successfully loaded into the SQL Server table. I suspected the issue might be related to the system locale. On Linux, the locale was set to en_US.UTF-8, while on Windows, it was Western European.

I changed the Linux locale to en_US.ISO-8859-15, but encountered the following error:

`~ could not bulk import
~ SQL Server BCP Import Command -> bcp 'dbo.ETQ_SUPPLIERS_STAGE_tmp' in '/tmp/sqlserver.dbo.etq_suppliers_stage_tmp.1732545272071.TVo1.csv' -S '****' -d 'RelianceGateway' -t ',' -m '1' '-w' -q -b '50000' -F '2' -e '/tmp/sqlserver.dbo.etq_suppliers_stage_tmp.1732545272082.TSi.error' -U '****' -P '****' -u
SQL Server BCP Import Error  ->
The table name specified exceeds the maximum allowed length.
`
Following recommendations, I adjusted the SAMPLE_SIZE and set bulk_import to false, but the error persisted. When I reverted the locale back to en_US.UTF-8, the process worked, but Chinese characters were not loaded correctly.

Any suggestions on how to resolve this issue?

**Comment by flarco** [comment]
Interesting that it worked for Windows.
Can you try this `use_bulk: false` in Linux (so it won't use `bcp`)?

The error you're getting is actually different: `The table name specified exceeds the maximum allowed length.`.
Can you try a shorted table name?
