### ISSUE TITLE
Cannot validate certificate for <IP address> because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by guaripete-github** [slingdata-io/sling-cli#48]
Getting following error starting with v1.0.52 using docker:

```
TLS Handshake failed: tls: failed to verify certificate: x509: cannot validate certificate for <IP address> because it doesn't contain any IP SANs
```

Previous versions pass connection test with same settings: 

```yaml
...
host: '<IP address>'
trust_cert: true
...
```

Not sure if related to the CLI or the container image failing to skip certificate verification.

**Comment by flarco** [comment]
Hi, can you try without docker to see if it works?
Like, install the CLI on your machine and connecting from there.

Also, can you try playing with the Parameters showed [here](https://docs.slingdata.io/connections/database-connections/sqlserver#additional-parameters)? Especially the certificate related ones.

**Comment by flarco** [comment]
Also, please upgrade to `v1.0.53`

**Comment by flarco** [comment]
Check out this: https://stackoverflow.com/a/73881123

> The subject(s) of the servers certificate do not match the URL you use in your code. Specifically you likely used an IP address for the URL and the server certificate does not contain a Subject Alternative Names extension (SAN) for this IP address (or any other IP address, hence "doesn't contain any IP SANs"). The cause of this mismatch is that you are using a wrong URL or that the server certificate is wrong.

**Comment by guaripete-github** [comment]
I was getting the error with v1.0.53 as well.

Found out that by defining the connection using URL style and passing parameters `encrypt=true&TrustServerCertificate=true` instead of using dbt profile style in env.yaml works.

Note that, previous to v1.0.52, it worked using dbt profile style with `trust_cert: true`.

**Comment by flarco** [comment]
That is interesting... the`trust_cert` key isn't being used by sling. Not sure how it worked before. In v1.0.52, the URL generator logic was changed so it can allow the user to easily pass more parameters.

Commit is [here](https://github.com/flarco/dbio/commit/ac03f8ebb0b7b9f0c4ec658e696b49b11e296e60#diff-b9adde9612439aa9df1ceebc36325654ae9d11a48c508b63995688809c1a1115).

Prior to 1.0.52, the ADO style connection string was being used, see [here](https://github.com/denisenkom/go-mssqldb#the-connection-string-can-be-specified-in-one-of-three-formats) for reference. In 1.0.52, the URL style is being used. I'm guessing the ADO style defaulted to trust the cert and not the URL style? 🤷
