### ISSUE TITLE
SFTP Ciphers

### ISSUE THREAD

**Issue by FRSR** [slingdata-io/sling-cli#49]
Receiving this error when connecting to a vendor's SFTP:

ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-gcm@openssh.com chacha20-poly1305@openssh.com aes128-ctr aes192-ctr aes256-ctr], server offered: [3des-cbc blowfish-cbc aes256-cbc aes128-cbc cast128-cbc]

Is it possible to specify different ciphers?

**Comment by flarco** [comment]
Hi, can you try with latest version `v1.0.54`? Added a few more acceptable ciphers.

**Comment by FRSR** [comment]
Works!  Thanks @flarco.
