### ISSUE TITLE
Sling docker image not starting

### ISSUE THREAD

**Issue by esenilsson** [slingdata-io/sling-cli#5]
Hi,

Mac version works great, however when trying out the docker image(slingdata/sling), i get the following failures on startup

`sling: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by sling)
sling: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by sling)
sling: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by sling)`

This is both on mac m1, but also on linux.  Any ideas?

**Comment by flarco** [comment]
Ah yes, i’ve seen this before. I’ll take a look soon.

**Comment by flarco** [comment]
@esenilsson fixed! Please pull `1.0.9` or `latest`. Thanks for reporting 👍.
