### ISSUE TITLE
Clickhouse Connections Issue Using Broken Down Format

### ISSUE THREAD

**Issue by banditelol** [slingdata-io/sling-cli#58]
## What Happened

When using broken down format of connecting with `clickhouse`, we found that the connection test is successful when using `default` user. When using other user we get the same error everytime. For example when one of my teammate is using their connection detail:
```yaml
  clickhouse_production:
    type: clickhouse
    host: [redacted_ip]
    user: [redacted_user]
    password: [redacted_password]
    database: 
```
we get the following error:
```bash
fatal:
~ 
~ could not test CLICKHOUSE_PRODUCTION (See https://docs.slingdata.io/sling-cli/environment)
~ could not connect to CLICKHOUSE_PRODUCTION
~ could not connect to database
code: 516, message: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.
```

## Possible Issue

Looking at the error message, we found that the following line is quite peculiar:

> code: 516, message: **default**: Authentication failed: password is incorrect, or there is no user with such name.

it seems like the clickhouse server receive connection information for `default` user instead of another user that my teammate's environment suggest. Looking into this, my first assumption is that there are conflicts with multiple configuration methods, but after making sure that they only use `~/.sling/env.yml` the problem persists. 

So I tried to understand how the connection test works and stumble upon this line in `farco/dbio` [repo](https://github.com/flarco/dbio/blob/1786d0effa851886a8f6a1e5ae5728b1cda28473/connection/connection.go#L511-L517):
```go
	case dbio.TypeDbClickhouse:
		setIfMissing("username", "")
		setIfMissing("password", "")
		setIfMissing("schema", c.Data["database"])
		setIfMissing("port", c.Type.DefPort())
		template = "clickhouse://{username}:{password}@{host}:{port}/{database}"
```
While other database configuration use `c.Data["user"]` to set `username` if missing, the CH case doesn't use that. So looking at the key name, I assume that `user` key in `env.yaml` won't work with clickhouse and instead either use URL format or use `username` as key instead.

## Current Workaround

As mentioned above currently I have two workarounds

### Using `username` key

By defining the user name in `username` key instead I got it working as expected
```yml
  clickhouse_production:
    type: clickhouse
    host: [redacted_host]
    username: [redacted_user]
    password: [redacted_password]
    database: 
```
but it introduces inconsistency in the yml config which is fine but I'd rather not to.

### Using URL pattern instead

As seen above, I assume the template will extract each key from the pattern. So `clickhouse://{username}:{password}@{host}:{port}/{database}` will detect value in `{username}` as `username` key. And after testing this with the same user, it worked as well.

## Proposed Solution

Currently the only option I could think of is using the same pattern as other database connection, i.e. using `c.Data["user"]` to fill the username part. To be like the following:

```diff
	case dbio.TypeDbClickhouse:
-		setIfMissing("username", "")
+		setIfMissing("username", c.Data["user"])
		setIfMissing("password", "")
		setIfMissing("schema", c.Data["database"])
		setIfMissing("port", c.Type.DefPort())
		template = "clickhouse://{username}:{password}@{host}:{port}/{database}"
```

**Comment by flarco** [comment]
Thank you for the details.

Obvious bug. I pushed this [commit](https://github.com/flarco/dbio/commit/fab19086b70dba8c7a36b17448f58e5f0bc73b16) to fix.

Will release [`v1.0.58`](https://github.com/slingdata-io/sling-cli/pull/57) soon.

**Comment by flarco** [comment]
v1.0.58 released!
