### ISSUE TITLE
Discover command hangs when recursive flag is not set for an S3 connection

### ISSUE THREAD

**Issue by hello-world-bfree** [slingdata-io/sling-cli#59]
Running `sling conns discover --folder s3://path/to/files/ --recursive my_conn` returns streams quickly, but `sling conns discover --folder s3://path/to/files/ my_conn` will just hang for a long, long while with no apparent exception.

**Comment by flarco** [comment]
Thanks, I am able to replicate. Looking into it.

**Comment by flarco** [comment]
v1.0.68 released, seems to have fixed this.
