### ISSUE TITLE
Problem when using MySQL as source with SSL true

### ISSUE THREAD

**Issue by esenilsson** [slingdata-io/sling-cli#6]
Hi,

Once again, thank you for an amazing tool. I have tried to work with a specific mysql source, that have SSL.

![CleanShot 2023-09-01 at 11 42 45](https://github.com/slingdata-io/sling-cli/assets/2824187/9c38879b-0ad9-468f-9159-5483423b2ccf)

Normally i would add an ?ssl=true, or something similar. That has no impact however. I tried to look at the dbio repo, but did not get any wiser.

Do you have any suggestion on how to set sslmode to true when using MySQL as source?

Thanks

**Comment by flarco** [comment]
Hi, thank you. Can you try `tls=true` as shown [here](https://github.com/go-sql-driver/mysql#tls)?

**Comment by esenilsson** [comment]
Hi,

`?tls=skip-verify` solved it for me. Thanks for your swift support
