### ISSUE TITLE
Bug: Snowflake Driver for GCP Customers

### ISSUE THREAD

**Issue by gu-xie** [slingdata-io/sling-cli#61]
Snowflake driver for GCP customers had a recent breaking behavior change with regards to PUT operation.
This requires forcing driver upgrades to at minimum for Go v1.6.17.

**Error when loading to Snowflake (GCP)**
`091032 (0A000): Your client app version, Go 1.6.15, is using a deprecated pre-signed URL for PUT. Please upgrade to a version that supports GCP downscoped token. See https://community.snowflake.com/s/article/faq-2023-client-driver-deprecation-for-GCP-customers.`

**Reference:** https://community.snowflake.com/s/article/faq-2023-client-driver-deprecation-for-GCP-customers

**Comment by flarco** [comment]
Will do 👍

**Comment by flarco** [comment]
v1.0.59 is released, can you try it? Feel free to reopen if issue persists.
