### ISSUE TITLE
Uppercase Bigquery dataset name support

### ISSUE THREAD

**Issue by kenneth-copeland** [slingdata-io/sling-cli#65]
When trying to setup a target BigQuery dataset as:

export SL_BQ_STAGE='
type: bigquery
project: atlas-datawarehouse-uat
dataset: ADG_TEST_DATASET
location: us-east1
key_file: /workspaces/dagnote/creds/bigquery-atlas-datawarehouse-uat.json
'
I get the following error:

2:55PM INF writing to target database [mode: incremental]
2:55PM INF execution failed
FYI there is a new sling version released (1.0.60). Please run pip install -U sling.
fatal:
~
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
~
~ execution failed
~ Could not WriteToDb
~ could not drop table adg_test_dataset.order_tmp
~ Error for drop table if exists adg_test_dataset.order_tmp
~ Could not execute SQL
~ Error executing drop table if exists adg_test_dataset.order_tmp
googleapi: Error 404: Not found: Dataset atlas-datawarehouse-uat:adg_test_dataset was not found in location US, notFound

BTW I tested with both version 1.59.0 and 1.60.0.

All works fine with a lowercase dataset name.

I am confused about whether it is truely using the location "us-east1", becuase the error reads:
  "Error 404: Not found: Dataset atlas-datawarehouse-uat:adg_test_dataset was not found in location US, notFound"

**Comment by flarco** [comment]
Hi, can you share your task config? Are you providing `` `ADG_TEST_DATASET`.`order` `` as the source stream name with the backticks?

About the location, I believe providing `US` should be enough. The error message `was not found in location US` is a catch-all error when the object cannot be found. Does not mean the location is incorrect.

**Comment by flarco** [comment]
closing, feel free to reopen
