### ISSUE TITLE
mssql: Invalid column name

### ISSUE THREAD

**Issue by guaripete-github** [slingdata-io/sling-cli#71]
Looks like the column casing for MSSQL is not preserved with the introduction of quotes in update-key expression. This can be an issue for case sensitive collations.
 
```sql
-- v1.0.60
WHERE GJ.CREATED > '2023-11-29 09:40:27.000'
```
```sql
-- v1.0.61
WHERE GJ."created" > '2023-11-29 09:40:27.000'
```
`mssql: Invalid column name 'created'.`

**Comment by flarco** [comment]
Thanks for raising @guaripete-github.
What version of MSSQL are you using?

I tried the following (with MSSQL 2017), and it all works (which is admittedly surprising to me, the quotes don't make a difference):

```sql
create table test31 ("CREATED" varchar);
insert into "test31" values ('1');

select "CREATED" from "test31" ;  -- works
select "CREaTED" from "test31" ;  -- works
select "created" from "test31" ;   -- works
```

**Comment by guaripete-github** [comment]
No problem! Thanks for looking into it.

I believe the issue surfaces in case sensitive collations: in my case a source server/database set with `Latin1_General_BIN`.

It could happen that your server's default collation is case insensitive e.g., `SQL_Latin1_General_CP1_CI_AS`. My target has the later and has no issues with

```sql
select max("created") from "test31";
```

even when the column definition is "CREATED" as in your example.

https://learn.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-server-collation?view=sql-server-ver16#server-collation-in-sql-server

**Comment by flarco** [comment]
Ok, pushed a commit. Key changes are here: https://github.com/slingdata-io/sling-cli/pull/73/commits/59626df2f47fc83714b5dcd3d165d9a56ea0ad2f#diff-52b3cf4f4953fc17c2c73c4532691012530c85a1e9961ccf4d945ef9b78e1c41R60-R66
where the column name is pulled from source and overwrites the provided update-key column with correctly cased column name before applying quotes. Same logic is used at target side before getting the max value (can be different system with different casing). I think this will be more robust.

Will release in 1.0.62 soon.

**Comment by flarco** [comment]
1.0.62 has been released! Closing this.

**Comment by guaripete-github** [comment]
Hey @flarco, looks like we are having a similar issue on the source side this time with version 1.2.2:

```
--- database.go:1469 GetTableColumns ---
did not find any columns for "dbo"."testtable". Perhaps it does not exists, or user does not have read permission.
```

The source collation is case sensitive and "dbo"."TESTTABLE" exists.

```sql
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TESTTABLE'
```

would work, but:

```sql
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'testtable'
```

wouldn't.

**Comment by flarco** [comment]
Hey, can you table adding quotes around your source stream table? Like
'"my-schema"."table_NAME"'

**Comment by guaripete-github** [comment]
🤦‍♂️That did the trick, thanks!
