### ISSUE TITLE
Incremental first-run execution failed with target database sqlserver

### ISSUE THREAD

**Issue by guaripete-github** [slingdata-io/sling-cli#72]
```log
fatal:
--- task_run.go:88 func1 ---
~ execution failed
--- task_run.go:606 runDbToDb ---
~ Could not get incremental value
--- task_func.go:197 getIncrementalValue ---
~ could not get max value for CREATED
--- database.go:1199 Query ---
~ Error with StreamRows
--- database.go:852 StreamRows ---
~ SQL Error for:
select max("created") as max_val from "psa"."yp110"
--- database.go:890 StreamRowsContext ---
mssql: Invalid object name 'psa.yp110'.
```

**Comment by tacastillo** [comment]
+1

Hi! I'm getting the same issue here when replicating, can be repro'd with sqlite.

Making the table first with a `full-refresh` and then changing the stream to incremental works.

**Comment by flarco** [comment]
Thanks for raising this, fixed here: https://github.com/slingdata-io/sling-cli/pull/73/commits/a0081582bf3eb336323aa4e324984d204413a50a

Will release 1.0.62 soon.

**Comment by tacastillo** [comment]
> Thanks for raising this, fixed here: https://github.com/slingdata-io/sling-cli/pull/73/commits/a0081582bf3eb336323aa4e324984d204413a50a
> 
> Will release 1.0.62 soon.

Thanks for the quick turnaround on this!

**Comment by PedramNavid** [comment]
@flarco is the best

**Comment by flarco** [comment]
1.0.62 has been released! Closing this.
