### ISSUE TITLE
[Feature Request] Support Application Default Credentials for BigQuery

### ISSUE THREAD

**Issue by rob-pomelo** [slingdata-io/sling-cli#74]
Thanks for awesome library! We typically avoid using service account keys anywhere for BigQuery as on Google Cloud you can typically just rely on the default creds which client libraries typically fetch from the metadata server (ex https://cloud.google.com/bigquery/docs/authentication/getting-started#application_default_credentials). Would be great if this could be supported (thus making key_file optional)

**Comment by flarco** [comment]
Hey, I checked out the link you shared (thanks!), and it was a simple change.  Going forward, it will not throw an error if `key_file` is not provided (also updated the docs).

Will release 1.0.62 soon with [applied changes](https://github.com/flarco/dbio/commit/7215e34686683d2b82dda9c34bb7c52f38fa9c1f#diff-950619fc8291a90237745578905e74c9bb946796b5683cb0640cbf6a6e092224R131-R134).

**Comment by rob-pomelo** [comment]
wow thank you so much for the quick turn around :)

**Comment by flarco** [comment]
1.0.62 has been released! Closing this.

**Comment by jmesterh** [comment]
I am having problems getting this to work using homebrew installed MacOS Sling v1.0.66:

env.yaml:
```
connections:
  BIGQUERY:
    type: bigquery
    dataset: my-redacted-dataset
    project: my-redacted-project
 ```

```
bash~/Projects/sling$ sling conns test BIGQUERY
fatal:
~ 
~ could not test BIGQUERY (See https://docs.slingdata.io/sling-cli/environment)
~ could not connect to BIGQUERY
~ Failed to get datasets
Get "https://bigquery.googleapis.com/bigquery/v2/projects/my-redacted-project/datasets?all=false&alt=json&pageToken=&prettyPrint=false": context canceled
```

**Comment by flarco** [comment]
Hi, so it used to work in older versions?

**Comment by jmesterh** [comment]
I don't know, this is the first time I've tried this application.

**Comment by flarco** [comment]
OK, should be good in next release (#99).
