### ISSUE TITLE
Allow expanding environment variables and file content in yaml configuration

### ISSUE THREAD

**Issue by nicosuave** [slingdata-io/sling-cli#75]
Just a convenience to help with those with unconventional infrastructure

Some examples might be:

`${POSTGRES_PASSWORD}`
`${file:/etc/secrets/POSTGRES_PASSWORD}`

**Comment by nicosuave** [comment]
I did see this!

Sure, just trying to compose the configuration from the sensitive bits I have already have stored elsewhere. For various reasons in this project, secrets are unfortunately already provided as just the sensitive components of the connection string as a volume mount inside files.

**Comment by nicosuave** [comment]
My first example is contrived, but the second more akin to my use case

**Comment by flarco** [comment]
For the second pattern, wouldn't `export POSTGRES="postgresql://myuser:${file:/etc/secrets/POSTGRES_PASSWORD}@host.ip:5432/mydatabase?sslmode=require"` work for you?

**Comment by nicosuave** [comment]
Yes, thanks!
