### ISSUE TITLE
Feature Request: Avro support

### ISSUE THREAD

**Issue by nicosuave** [slingdata-io/sling-cli#76]
Hello again— would you consider adding Avro support for filesystems?

**Comment by flarco** [comment]
Was actually not bad since that is a good lib available (https://github.com/linkedin/goavro). 
Added reading capabilities here: https://github.com/flarco/dbio/commit/01091004eaf97869fbb6a89ccccc90954776f4b6

Will release v1.0.63 soon.

**Comment by nicosuave** [comment]
You're a machine @flarco I appreciate you!

**Comment by flarco** [comment]
Closing for now, reopen if needed!
