### ISSUE TITLE
Feature Request: SAS7BDAT

### ISSUE THREAD

**Issue by bvallier** [slingdata-io/sling-cli#78]
Is it possible to add SAS7BDAT files to file formats?

**Comment by flarco** [comment]
Ok, was able to add it in there. v1.0.63 is released.
Could you give it a shot? See docs [here](https://docs.slingdata.io/sling-cli/run/file-to-database#local-storage-sas7bdat-database) on reading `sas7bdat` files.

**Comment by bvallier** [comment]
WOW - thanks! Let me test.

**Comment by bvallier** [comment]
Works as advertised. Loaded a 4gb file with 10M+ rows locally and read into snowflake. Perfect!
