### ISSUE TITLE
mssql unique identifier is mapped to a binary string

### ISSUE THREAD

**Issue by creativedutchmen** [slingdata-io/sling-cli#8]
When running a MSSQL sync (thanks for updating!) where the source tables has UUID columns, the following warning is emitted in the logs:

```
WRN using string since type 'uniqueidentifier' not mapped for col 'Id': ""
```

No big deal, because UUIDs can be stored as strings too, no problem. However, when pushing the data to ClickHouse, it seems the mapping is not entirely correct, because an example Id looks like `�4�k@�听Ur�8`

ClickHouse also supports UUIDs, so there is not really a need to convert to string first. Is there a way to configure this?

**Comment by flarco** [comment]
👍 will take a look soon.

**Comment by flarco** [comment]
Hi @creativedutchmen, can you try the following with `v1.0.29`, there is now a `transforms` options with `parse_uuid` :
```
./sling run --src-conn MSSQL_URL --src-stream 'select date,id from dbo.my_table3' --stdout
12:15PM INF connecting to source database (sqlserver)
12:15PM INF reading from source database
12:15PM INF writing to target stream (stdout)
date,id
2023-01-01 00:00:00.000000 +00,��I�e��B��p�Q��
2023-02-01 00:00:00.000000 +00,�ugH�@�P/�J�q
12:15PM INF wrote 2 rows [40 r/s]
12:15PM INF execution succeeded
```

with `--src-options '{transforms: [ parse_uuid ]}`:
```
./sling run --src-conn MSSQL_URL --src-stream 'select date,id from dbo.my_table3' --src-options '{transforms: [ parse_uuid ]}' --stdout
9:57AM INF connecting to source database (sqlserver)
9:57AM INF reading from source database
9:57AM INF writing to target stream (stdout)
date,id
2023-01-01 00:00:00.000000 +00,bfe549b5-65ac-a142-89c4-708b518804d9
2023-02-01 00:00:00.000000 +00,00d37502-6748-8540-8e50-2f00bf4acb71
9:57AM INF wrote 2 rows [14 r/s]
9:57AM INF execution succeeded
```
