### ISSUE TITLE
Iceberg support

### ISSUE THREAD

**Issue by toddy86** [slingdata-io/sling-cli#81]
Hi, 

Are there any considerations to add Apache Iceberg as a destination table format (on S3, GCS etc)?

Similar to the request that I've seen for Delta [here](https://github.com/slingdata-io/sling-cli/issues/26)

All the best

Todd

**Comment by flarco** [comment]
Thanks, adding some links:
- https://github.com/apache/iceberg-go
- https://pkg.go.dev/github.com/apache/arrow/go/v14@v14.0.0
- https://github.com/apache/arrow/tree/main/go

**Comment by alberttwong** [comment]
The easiest way may be to use DuckDB with Iceberg and executing it behind the scenes.  https://duckdb.org/docs/extensions/iceberg.html

**Comment by parsingeye** [comment]
Alternatively, iceberg support can be achieved through AWS Athena support, the way `dtl` supports it https://dlthub.com/docs/dlt-ecosystem/destinations/athena#additional-destination-options

**Comment by alberttwong** [comment]
The problem is that it's not enough to support iceberg format.  You also need to register those files/data into HMS so that projects like Trino and StarRocks can be a SQL query engine to the data within those formats.

**Comment by flarco** [comment]
Added in #357 

See https://blog.slingdata.io/reading-apache-iceberg-data-with-sling

Closing.
