### ISSUE TITLE
Decimal precision is incorrectly casted for SQL server source and parquet target

### ISSUE THREAD

**Issue by nixent** [slingdata-io/sling-cli#86]
When reading from `SQL server` table as source and `parquet` as target, field with type `decimal(32, 16)` is written as `decimal(19, 6)`.
How field types are captured for SQL server and how to control column types?

**Comment by flarco** [comment]
Yes, it's defined here: 
https://github.com/flarco/dbio/blob/01091004eaf97869fbb6a89ccccc90954776f4b6/iop/parquet.go#L218-L220

Hard-coded right now.... we can make this as an optional input, but not quite sure yet on the best way to do this.
Any suggestions on how to input this into the sling config?

**Comment by nixent** [comment]
I'd suggest adding `decimal_precision` parameter to `target_options`, maybe as tuple (precision, scale) and default (19, 6) as it is now.


On a separate note, `timestamp_precision` might be needed as well, with values 0 - 9 (from seconds to nanoseconds), default is 6

**Comment by flarco** [comment]
Ok, made some changes. It should be automatic for your use-case, sql server gives datatypes upon `SELECT`, and sling obtains precision/scale then. When obtained, it will pass it to the parquet file. For `timestamp_precision`, I put `9` / `NANO` as the default.
Version `1.0.65` is released, give it a shot.

**Comment by nixent** [comment]
Wonderful, thank you. I'll test it on Monday
