### ISSUE TITLE
Parquet target version support

### ISSUE THREAD

**Issue by nixent** [slingdata-io/sling-cli#87]
When writing to `parquet` target, format version is 1.0. Is there any support for later versions of parquet format? For instance pyarrow writes version 2.6 by default.

Sample of metadata of file created by Sling:   
```
metadata: <pyarrow._parquet.FileMetaData object at 0x0000028E5EB3B970>
  created_by: flarco/dbio
  num_columns: 84
  num_rows: 10395
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 8923
```

**Comment by flarco** [comment]
The problem is that sling uses https://github.com/fraugster/parquet-go which is not really under maintenance anymore.
The plan is to use https://github.com/parquet-go/parquet-go, which is maintained, but structure is a bit different and requires more time to implement.
