### ISSUE TITLE
Curl Install no longer working?

### ISSUE THREAD

**Issue by BullShinkles** [slingdata-io/sling-cli#88]
I will install the tar and thank you, this is an awesome project..., but I did want to say that CLI Transfer using: curl -LO 'https://f.slingdata.io/linux/sling' && chmod +x sling  appears to be no longer working.

**Comment by flarco** [comment]
Thanks! I have actually been meaning to update the installation command snippet for linux, see below. Will propagate!

```shell
curl -LO 'https://github.com/slingdata-io/sling-cli/releases/latest/download/sling_linux_amd64.tar.gz' \
  && tar xf sling_linux_amd64.tar.gz \
  && rm -f sling_linux_amd64.tar.gz \
  && chmod +x sling
```
