### ISSUE TITLE
Sling Changes File Path Capitalization Unintentionally.

### ISSUE THREAD

**Issue by KacemHamza97** [slingdata-io/sling-cli#9]
Why does sling change the capitalization of the file path when I use the command or the python lib to load a PostgreSQL table into a CSV file? Specifically, I specify the path as 'file:///Downloads/assets/file.csv,' but sling saves the CSV file to 'downloads/assets' with lowercase letters. This behavior seems unexpected.

**Comment by flarco** [comment]
@KacemHamza97  Could you share the command you are running (or config file)? Also, what version/OS?
I just tested on my macbook, `sling run --src-conn DUCKDB --src-stream 'select 1 a, 2 b' --tgt-object 'file:///Users/fritz/Downloads/my_file.csv'`, it writes correctly, without lower-casing.

**Comment by KacemHamza97** [comment]
Hey flarco :), yes sure

command; 
export MY_SOURCE_DB='postgresql://postgres:postgres@localhost:5432/dvdrental'
sling run --src-conn MY_SOURCE_DB --src-stream "film" --tgt-object "file:///home/hamza/Downloads/assets/file.csv"
OS: Ubuntu 20.04.6 LTS

**Comment by flarco** [comment]
Thank you, I was able to reproduce. I did not know that on Mac, paths are case-insensitive!

Furthermore, I found where it's happening: https://github.com/slingdata-io/sling-cli/commit/0cf78bd1965ea11abca1a0fe246272f125c86fa9

But I can't remember why I put `strings.ToLower(` there :) 

I'll push an update later today after running some tests.

**Comment by flarco** [comment]
Released! Please try `v1.0.18`
