### ISSUE TITLE
Parquet files with Decimal fields are written as String

### ISSUE THREAD

**Issue by nixent** [slingdata-io/sling-cli#92]
If `parquet` files produced by Sling contain fields of `decimal` type the file is corrupted and it is not possible to read it.
Error message from pyarrow: `pyarrow.lib.ArrowInvalid: Invalid BYTE_ARRAY length for decimal128(32, 16)`

The error comes from [this validation](https://github.com/apache/arrow/blob/3943f744722031d2706d8ed99c1b06caf5429976/cpp/src/parquet/arrow/reader_internal.cc#L615C42-L615C53)

**Comment by flarco** [comment]
Ah, this is unfortunate. Might be the driver. Can you confirm that reading the same parquet file with sling works?
 
Here is the logic setting the decimal: https://github.com/flarco/dbio/blob/main/iop/parquet.go#L219-L230
Any suggestions?

**Comment by nixent** [comment]
Reading with Sling works. I tried reading with `pyarrow` and `Spark`, and can read I don't select `decimal` columns. Selecting decimal column results in error. It seems to be some sort of compatibility issue with decimal type. I can see there were multiple issues reported for `fraugster
/parquet-go`, but they are resolved already. Will try to investigate that

**Comment by flarco** [comment]
hey @nixent, do you mind building https://github.com/slingdata-io/sling-cli/pull/99 locally and testing? Instructions are on the main README. Finally using https://github.com/parquet-go/parquet-go, however not sure the decimal type are working well.

**Comment by nixent** [comment]
@flarco, sure, I'll test it.
Thanks for the quick change of the parquet package!

**Comment by nixent** [comment]
@flarco getting issues building the project, turns out that C compiler is required to build godror dependency. Would it be possible to build 1.0.68 and upload somewhere? Sorry for bothering, didn't work with go before and would rather focus on testing than figuring out how to build go project.

**Comment by flarco** [comment]
Sure, what operating system are you using?

**Comment by nixent** [comment]
For local testing - Windows and for production loads - Linux. Can test with either of them

**Comment by flarco** [comment]
Here you go:
- Windows: https://github.com/slingdata-io/sling-cli/releases/download/untagged-d57ef8557e7e69f57f36/sling-win.exe
- Linux: https://github.com/slingdata-io/sling-cli/releases/download/untagged-038a7f14cc5f84fda2a2/sling-linux

**Comment by flarco** [comment]
Closing for now.

**Comment by nixent** [comment]
@flarco finally got time to test it with 1.0.69. Seems decimal type is not recognized and `decimal(32,16)` values are written as `string` values

**Comment by flarco** [comment]
Thanks @nixent , yes I was hoping that wasn’t a big deal cause I could get the new driver to write decimal type properly, kept erroring out. I may look at it again some other time. The positive about using string is that the precision is kept intact. 

What kind of issues do you foresee in keeping it as string? I am unsure of the ramifications. I figure the client reading the parquet file can just convert to decimal at runtime, or using dbt in a database.

**Comment by nixent** [comment]
@flarco main issues with storing decimal values in string:
- loss of column statistics in parquet. Might be crucial for reading big files. 
- conversion to decimal type is prone to loss of precision. In cases where consumers of the parquet cannot get precision of the original column in the DB they might resort to sampling which is not always accurate.
- storage requirements are higher

**Comment by flarco** [comment]
Thanks, re-opening!

**Comment by nixent** [comment]
@flarco the issue is labeled as `external`. Do you have reference to what it depends on?
Decimals written as String are creating issues downstream of parquet files and I'm looking for ways to fix that.

**Comment by flarco** [comment]
@nixent would be great to have help on this.

Here is the reference: https://github.com/parquet-go/parquet-go/issues/65. It seems like no progress is made there.

I've tried to use `FIXED_LEN_BYTE_ARRAY` with no success. The data is written strangely.

Here is the relevant part to modify for testing: https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/iop/parquet.go#L284-L291

I just added a test here in branch v1.1.6: https://github.com/slingdata-io/sling-cli/blob/v1.1.6/core/dbio/iop/parquet_test.go#L126-L172

you could just modify `parquet.go#L284-L291` and run `go test -run TestParquetDecimal` from folder `core/dbio/iop`.

It should output something like this:

```
$ go test -run TestParquetDecimal
2024-02-16 07:56:53 INF /tmp/test.parquet
2024-02-16 07:56:53 INF correctIntValues => [672661,451113,357695,793768,83763]
2024-02-16 07:56:53 INF correctDecValues => ["291599.47419","475008.537045","79192.940985","131354.508749","481296.703118"]
PASS
ok      github.com/slingdata-io/sling-cli/core/dbio/iop 0.461s
```

Than open the parquet file with your reader to check the values. It's very strange, whenever I try to use `parquet.Decimal`, like `n = parquet.Decimal(4, 12, parquet.FixedLenByteArrayType(16))`, reading it back with `sling run --src-stream file:///tmp/test.parquet --stdout -d` is good but, reading with `pyarrow.parquet` (using [check_parquet.py](https://github.com/slingdata-io/sling-cli/blob/v1.1.6/core/dbio/scripts/check_parquet.py)) has totally different numbers, weird long numbers. 🤔 

```
$ go test -run TestParquetDecimal
2024-02-16 08:09:11 INF /tmp/test.parquet
2024-02-16 08:09:11 INF correctIntValues => [607387,994206,287897,828260,22730]
2024-02-16 08:09:11 INF correctDecValues => ["-1.2","926163.422999566","706782.46194342","174661.571733779","341023.124514334"]
PASS
ok      github.com/slingdata-io/sling-cli/core/dbio/iop 0.479s

fritz@mbp:sling-cli/core/dbio/iop$ python sling-cli/core/dbio/scripts/check_parquet.py
num_row_groups: 1
metadata: <pyarrow._parquet.FileMetaData object at 0x1050aeca0>
  created_by: github.com/parquet-go/parquet-go
  num_columns: 2
  num_rows: 5
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 318
compression: UNCOMPRESSED
<pyarrow._parquet.ParquetSchema object at 0x10660b240>
required group field_id=-1  {
  required int64 field_id=-1 col_big_int (Int(bitWidth=64, isSigned=true));
  required fixed_len_byte_array(16) field_id=-1 col_decimal_type (Decimal(precision=12, scale=4));
}

pyarrow.Table
col_big_int: int64 not null
col_decimal_type: decimal128(12, 4) not null
----
col_big_int: [[607387,994206,287897,828260,22730]]
col_decimal_type: [[6007061930863931452452569328350396.4160,7602670975173957046495786249195600.0310,7335786964243940524359023732787486.3616,6541880710107210505501841765025600.0825,6806162487823302401555056981456736.7476]]

fritz@mbp:sling-cli/core/dbio/iop$ sling run --src-stream file:///tmp/test.parquet --stdout -d
2024-02-16 08:09:22 DBG Sling version: 1.1.3 (darwin arm64)
2024-02-16 08:09:22 DBG type is file-file
2024-02-16 08:09:22 DBG using source options: {"trim_space":false,"empty_as_null":true,"header":true,"compression":"AUTO","null_if":"NULL","datetime_format":"AUTO","skip_blank_lines":false,"delimiter":",","max_decimals":-1}
2024-02-16 08:09:22 DBG using target options: {"datetime_format":"auto","max_decimals":-1,"use_bulk":true,"add_new_columns":true,"adjust_column_type":false,"column_casing":"source"}
2024-02-16 08:09:22 INF reading from source file system (file)
2024-02-16 08:09:22 DBG listing path: file:///tmp/test.parquet
2024-02-16 08:09:22 DBG ds.1708081762867.dGg, reading datastream from /tmp/test.parquet [format=parquet]
2024-02-16 08:09:22 INF writing to target stream (stdout)
col_big_int,col_decimal_type
607387,-1.2
994206,926163.422999566
287897,706782.46194342
828260,174661.571733779
22730,341023.124514334
2024-02-16 08:09:22 DBG wrote 148 B: 5 rows [411 r/s]
2024-02-16 08:09:22 INF wrote 5 rows to stdout [410 r/s]
2024-02-16 08:09:22 INF execution succeeded

$ ipython
Python 3.10.10 (v3.10.10:aad5f6a891, Feb  7 2023, 08:47:40) [Clang 13.0.0 (clang-1300.0.29.30)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pyarrow.parquet as pq

In [2]: pq.read_pandas("/tmp/test.parquet").to_pandas()
Out[2]: 
   col_big_int                         col_decimal_type
0       607387  6007061930863931452452569328350396.4160
1       994206  7602670975173957046495786249195600.0310
2       287897  7335786964243940524359023732787486.3616
3       828260  6541880710107210505501841765025600.0825
4        22730  6806162487823302401555056981456736.7476
```

**Comment by flarco** [comment]
@nixent spent the weekend on this.
Found out that the Apache Arrow project has a Golang Parquet lib here: https://github.com/apache/arrow/tree/main/go

I'm about to release v1.1.6 with it, decimals should be working now!

[Attached](https://github.com/slingdata-io/sling-cli/files/14331978/test1.parquet.zip) is a test file, if you want to inspect it, that would be great.

```
num_row_groups: 1
metadata: <pyarrow._parquet.FileMetaData object at 0x1021cdda0>
  created_by: parquet-go version 16.0.0-SNAPSHOT
  num_columns: 7
  num_rows: 1000
  num_row_groups: 1
  format_version: 2.6
  serialized_size: 877
compression: SNAPPY
<pyarrow._parquet.ParquetSchema object at 0x100fbb140>
required group field_id=-1 schema {
   binary field_id=-1 id (Decimal(precision=28, scale=9));
   binary field_id=-1 first_name (String);
   binary field_id=-1 last_name (String);
   binary field_id=-1 email (String);
   boolean field_id=-1 target;
   int64 field_id=-1 create_dt (Timestamp(isAdjustedToUTC=true, timeUnit=nanoseconds, is_from_converted_type=false, force_set_converted_type=false));
   binary field_id=-1 rating (Decimal(precision=28, scale=9));
}
```

**Comment by nixent** [comment]
@flarco wow, that is very great news. Thank you very much for the great effort you are putting into the project!

will test it once v1.1.6 is out

**Comment by flarco** [comment]
Closing this. Feel free to re-open if decimal issues arise.

**Comment by nixent** [comment]
@flarco tested decimals with the 1.1.6 release, even though `print(data)` shows file content, it is failing when accessing the data from other libraries, pyarrow.parquet and DuckDB in my case . Seems that the issue is caused by type decimals are stored in, IsFixedWidth attribute.
I have created paquet file with Pandas and Sling with same content. Pandas writes decimals with `FIXED_LEN_BYTE_ARRAY`, while Sling uses `BYTE_ARRAY` 

Comparison of the two tools for same `decimal(28,9)`:
Hope that can help in troubleshooting

`Pandas` generated arrow schema:
``` JSON
    {
      "DataType": {
        "TypeId": 22,
        "Name": "decimal128",
        "IsFixedWidth": true
      },
      "Name": "rating",
      "IsNullable": false,
      "HasMetadata": false,
      "Metadata": null
    }
```

`Pandas` generated metadata:
``` JSON
     {
        "Path": "rating",
        "Type": "FIXED_LEN_BYTE_ARRAY",
        "TypeLength": 12,
        "LogicalType": {
          "Name": "DECIMAL",
          "Scale": 9,
          "Precision": 28
        },
        "RepetitionType": "REQUIRED",
        "ConvertedType": "DECIMAL",
        "Children": []
      }
```


`Sling` generated metadata:
 ``` JSON
     {
        "Path": "rating",
        "Type": "BYTE_ARRAY",
        "TypeLength": null,
        "LogicalType": {
          "Name": "DECIMAL",
          "Scale": 9,
          "Precision": 28
        },
        "RepetitionType": "3",
        "ConvertedType": "DECIMAL",
        "Children": []
      }
```

**Comment by flarco** [comment]
That helps, thanks. Re-opening.

**Comment by flarco** [comment]
Can you share your pyarrow code that youre' using to test?

I ran the below in iPython, and it's reading it fine.

```python
In [1]: import pyarrow.parquet as pq
   ...: import sys


In [2]: 

In [2]: file = pq.ParquetFile("/tmp/test.parquet")

In [3]: data = file.read()

In [4]: data[0]
Out[4]: 
<pyarrow.lib.ChunkedArray object at 0x107a12750>
[
  [
    "hello",
    "hello2"
  ]
]

In [5]: data[3]
Out[5]: 
<pyarrow.lib.ChunkedArray object at 0x107aad490>
[
  [
    12.330000000,
    -121.330000000
  ]
]

In [6]: data[4]
Out[6]: 
<pyarrow.lib.ChunkedArray object at 0x120d7d580>
[
  [
    12.33,
    -121.33
  ]
]

In [7]:
```

Also, what error are you getting in DuckDB?

**Comment by nixent** [comment]
@flarco the code is similar to your test with exception that my file has multiple columns with decimals with different precision+scale and decimal column is not last column in the file. I suspect some sort of overflow.

```PY
import pyarrow.parquet as pq

file_path = ...
file = pq.ParquetFile(file_path)

print(f'num_row_groups: {file.num_row_groups}')
print(f'metadata: {file.metadata}')
print(f'compression: {file.metadata.row_group(0).column(0).compression}')
print(file.schema)

table= file.read() 
```

It fails with error:
`pyarrow.lib.ArrowInvalid: Length of byte array passed to Decimal128::FromBigEndian was 0, but must be between 1 and 16`

What caught my attention is that pandas and pyarow use FIXED_LEN_BYTE_ARRAY to define decimal type. So maybe that is the reason why I cannot read parquet produced by Sling.

**Comment by flarco** [comment]
@nixent  Can you test out the attached file? just generated it with some changes.
[test.1.parquet.zip](https://github.com/slingdata-io/sling-cli/files/14350674/test.1.parquet.zip)

**Comment by flarco** [comment]
Another to test, with `prec 32, scale 16`.

[test.2.parquet.zip](https://github.com/slingdata-io/sling-cli/files/14350732/test.2.parquet.zip)

**Comment by nixent** [comment]
@flarco Both files work fine and parquet type is FIXED_LEN_BYTE_ARRAY. Thank you for the quick fix.

``` JSON
{
    "Path": "price",
    "Type": "FIXED_LEN_BYTE_ARRAY",
    "TypeLength": 16,
    "LogicalType": {
      "Name": "DECIMAL",
      "Scale": 16,
      "Precision": 32
    },
    "RepetitionType": "REQUIRED",
    "ConvertedType": "DECIMAL",
    "Children": []
}
```

**Comment by flarco** [comment]
Closing. About to release 1.1.7
